apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_BROKERS
            - name: BROKER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: selfcare-v2
                  key: SELFCARE_BROKER_CONNECTION_STRING
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_GROUP_ID
            - name: SELFCARE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: SELFCARE_TOPIC
            - name: RESET_CONSUMER_OFFSETS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: RESET_CONSUMER_OFFSETS
            - name: INTEROP_PRODUCT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: INTEROP_PRODUCT
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ALLOWED_ORIGINS
            - name: TENANT_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: TENANT_PROCESS_URL
            - name: INTERNAL_JWT_KID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: INTERNAL_JWT_KID
            - name: INTERNAL_JWT_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: INTERNAL_JWT_SUBJECT
            - name: INTERNAL_JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: INTERNAL_JWT_ISSUER
            - name: INTERNAL_JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: INTERNAL_JWT_AUDIENCE
            - name: INTERNAL_JWT_SECONDS_DURATION
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: INTERNAL_JWT_SECONDS_DURATION
