apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  ESERVICE_MONITORING_EXPORT_BUCKET: "{{ESERVICE_MONITORING_EXPORT_BUCKET}}"
  ESERVICE_MONITORING_EXPORT_FILENAME: "{{ESERVICE_MONITORING_EXPORT_FILENAME}}"
  TENANTS_COLLECTION_NAME: "{{TENANTS_COLLECTION_NAME}}"
  ESERVICES_COLLECTION_NAME: "{{ESERVICES_COLLECTION_NAME}}"