#!/bin/bash

ESERVICE_TEMPLATE_PROCESS_PROCESS_RESOURCE_CPU="500m"
ESERVICE_TEMPLATE_PROCESS_PROCESS_RESOURCE_MEM="2Gi"
ESERVICE_TEMPLATE_PROCESS_DOCUMENTS_PATH="eservice-template/docs"
ESERVICE_TEMPLATE_PROCESS_STORAGE_CONTAINER="interop-application-documents-dev"
