#!/bin/bash

PRIVACY_NOTICES_LANGS=it
PRIVACY_NOTICES_CONTENT_STORAGE_BUCKET="interop-privacy-notices-content-dev-es1"
PRIVACY_NOTICES_HISTORY_STORAGE_BUCKET="interop-privacy-notices-history-dev-es1"

JOB_ONE_TRUST_NOTICES_RESOURCE_CPU="500m"
JOB_ONE_TRUST_NOTICES_RESOURCE_MEM="1Gi"
