#!/bin/bash

PURPOSE_PROCESS_STORAGE_TYPE="S3"
PURPOSE_PROCESS_STORAGE_CONTAINER="interop-application-documents-dev-es1"
PURPOSE_PROCESS_STORAGE_ENDPOINT=""

PURPOSE_PROCESS_RESOURCE_CPU="500m"
PURPOSE_PROCESS_RESOURCE_MEM="2Gi"
