apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      initContainers:
        - name: migrate-db
          image: flyway/flyway:8.2.3
          args: 
            - migrate
          envFrom:
            - configMapRef:
                name: {{SERVICE_NAME}}
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://{{POSTGRES_HOST}}:{{POSTGRES_PORT}}/$(POSTGRES_DB)
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USR
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PSW
            - name: FLYWAY_CREATE_SCHEMAS
              value: "true"
            - name: FLYWAY_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_SCHEMA
            - name: FLYWAY_PLACEHOLDER_REPLACEMENT
              value: "true"
            - name: FLYWAY_PLACEHOLDERS_APPLICATIONSCHEMA
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_SCHEMA
            - name: POSTGRES_DB
              value: {{POSTGRES_DB_NAME}}
          volumeMounts:
            - name: migrations-files
              mountPath: "/flyway/sql"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: POSTGRES_HOST
              value: "{{POSTGRES_HOST}}"
            - name: POSTGRES_PORT
              value: "{{POSTGRES_PORT}}"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_DB
            - name: POSTGRES_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_SCHEMA
            - name: POSTGRES_USR
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USR
            - name: POSTGRES_PSW
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PSW
      volumes:
        - name: migrations-files
          projected:
            sources:
              - configMap:
                  name: event-store-migrations
