apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ACCEPTED_AUDIENCES
            - name: STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_TYPE
            - name: STORAGE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_CONTAINER
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_ENDPOINT
            - name: ESERVICE_DOCS_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ESERVICE_DOCS_PATH
            - name: ENABLED_PROJECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ENABLED_PROJECTIONS
            - name: PERSISTENCE_EVENTS_QUEUE_URL
              value: "{{AWS_SQS_DOMAIN}}/{{AWS_ACCOUNT_ID}}/{{PERSISTENCE_QUEUE_NAME}}"