apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  INTERNAL_JWT_KID: "{{RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{INTERNAL_JWT_SUBJECT}}"
  INTERNAL_JWT_ISSUER: "{{INTERNAL_JWT_ISSUER}}"
  INTERNAL_JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
  INTERNAL_JWT_SECONDS_DURATION: "{{IPA_CERTIFIED_ATTRIBUTES_IMPORTER_JWT_DURATION_SECONDS}}"

  INSTITUTIONS_URL: "{{IPA_INSTITUTIONS_URL}}"
  AOO_URL: "{{IPA_AOO_URL}}"
  UO_URL: "{{IPA_UO_URL}}"
  INSTITUTIONS_CATEGORIES_URL: "{{IPA_CATEGORIES_URL}}"
  ATTRIBUTE_CREATION_WAIT_TIME: "{{IPA_CERTIFIED_ATTRIBUTES_IMPORTER_ATTRIBUTE_CREATION_WAIT_MS}}"
  ECONOMIC_ACCOUNT_COMPANIES_ALLOWLIST: "{{ECONOMIC_ACCOUNT_COMPANIES_ALLOWLIST}}"



