apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "dev-pagopa-interop-authorization-updater"
  KAFKA_GROUP_ID: "authorization-updater"
  KAFKA_TOPICS: "event-store.dev-refactor_catalog.events"
  RSA_KEYS_IDENTIFIERS: {{RSA_KEYS_IDENTIFIERS}}
  KMS_MAX_ACQUISITION_TIMEOUT_SECONDS: "10"
  GENERATED_JWT_SECONDS_TO_EXPIRE: "60"
  GENERATED_JWT_ISSUER: "dev-refactor.interop.pagopa.it"
  GENERATED_JWT_SUBJECT: "dev-refactor.interop-attributes-loader"
  GENERATED_JWT_AUDIENCE: "refactor.dev.interop.pagopa.it/internal"
