apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "dev-pagopa-interop-authorization-updater"
  KAFKA_GROUP_ID: "authorization-updater"
  KAFKA_BROKERS: {{KAFKA_BROKERS}}
  KAFKA_TOPICS: "event-store.catalog.events,event-store.agreement.events"
