apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "dev-pagopa-interop-authorization-updater"
  KAFKA_GROUP_ID: "authorization-updater"
  KAFKA_BROKERS: {{KAFKA_BROKERS}}
  KAFKA_TOPICS: "event-store.catalog.events,event-store.agreement.events"
  AUTH_MNGT_SERVICE_URL: "interop-be-authorization-management.dev-refactor.svc.cluster.local"
  RSA_KEYS_IDENTIFIERS: {{RSA_KEYS_IDENTIFIERS}}
  KMS_MAX_ACQUISITION_TIMEOUT_SECONDS: 10
  GENERATED_JWT_SECONDS_TO_EXPIRE: 60
  GENERATED_JWT_ISSUER: "dev-refactor.interop.pagopa.it"
  GENERATED_JWT_SUBJECT: "dev-refactor.interop-attributes-loader"
  GENERATED_JWT_AUDIENCE: "refactor.dev.interop.pagopa.it/internal"
