apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  ARCHIVING_ESERVICES_QUEUE_URL: "{{ARCHIVING_ESERVICES_QUEUE_URL}}"
  CATALOG_PROCESS_URL: "http://{{CATALOG_PROCESS_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{CATALOG_PROCESS_APPLICATION_PATH}}/{{CATALOG_PROCESS_INTERFACE_VERSION}}"
  AGREEMENTS_COLLECTION_NAME: "{{AGREEMENTS_COLLECTION_NAME}}"
  ESERVICES_COLLECTION_NAME: "{{ESERVICES_COLLECTION_NAME}}"
        