bases:
- ../../../base
patchesStrategicMerge:
- ../../../commons/database/read-model.yaml
- deployment.yaml
- configmap.yaml
patches:
  - target:
      kind: Deployment
      name: interop-be-eservice-descriptors-archiver
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe


