apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  POSTGRES_DB: "{{POSTGRES_DB_NAME}}"
  POSTGRES_SCHEMA: "{{NAMESPACE}}_tenant"
  CQRS_PROJECTION_COLLECTION_NAME: "tenants"
  ACCEPTED_AUDIENCES: "{{UI_JWT_AUDIENCE}},{{M2M_JWT_AUDIENCE}},{{INTERNAL_JWT_AUDIENCE}}"
