apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "dev-pagopa-interop-catalog"
  KAFKA_GROUP_ID: "catalog-readmodel-writer"
  CATALOG_TOPIC: "event-store.catalog.events"
