apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  EVENTSTORE_DB_SCHEMA: "{{NAMESPACE}}_purpose"
  
  RISK_ANALYSIS_DOCS_PATH: "{{NAMESPACE}}/risk-analysis/docs"

  ACCEPTED_AUDIENCES: "{{UI_JWT_AUDIENCE}},{{M2M_JWT_AUDIENCE}}"
