apiVersion: v1
kind: Service
metadata:
  # Required only until the service is exposed in the LB
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /{{PURPOSE_PROCESS_APPLICATION_PATH}}/{{PURPOSE_PROCESS_INTERFACE_VERSION}}/status
    alb.ingress.kubernetes.io/healthcheck-port: "{{SCALA_BACKEND_SERVICE_PORT}}"
  name: {{PURPOSE_PROCESS_SERVICE_NAME}}
  namespace: {{NAMESPACE}}