apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  ACCEPTED_AUDIENCES: "{{UI_JWT_AUDIENCE}},{{M2M_JWT_AUDIENCE}},{{INTERNAL_JWT_AUDIENCE}}"
  ATTRIBUTE_REGISTRY_MANAGEMENT_URL: "{{ATTRIBUTE_REGISTRY_MANAGEMENT_URL}}"
  PARTY_REGISTRY_PROXY_URL: "http://{{PARTY_REGISTRY_PROXY_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{PARTY_REGISTRY_PROXY_APPLICATION_PATH}}/{{PARTY_REGISTRY_PROXY_INTERFACE_VERSION}}"
