apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-agreement-email-sender"
  KAFKA_GROUP_ID: "{{NAMESPACE}}-agreement-email-sender"
  
  AWS_SES_ENDPOINT: "email.{{AWS_REGION}}.amazonaws.com"

  PEC_SMTP_ADDRESS: "{{PEC_SMTP_ADDRESS}}"
  PEC_SMTP_PORT: "{{PEC_SMTP_PORT}}"
  PEC_SMTP_SECURE: "{{PEC_SMTP_SECURE}}"

  SMTP_ADDRESS: "{{SMTP_ADDRESS}}"
  SMTP_PORT: "{{SMTP_PORT}}"
  SMTP_SECURE: "{{SMTP_SECURE}}"
  SENDER_MAIL: "{{NOTIFICATION_SENDER_MAIL}}"
  SENDER_LABEL: "{{NOTIFICATION_SENDER_LABEL}}"

  INTEROP_FE_BASE_URL: "{{INTEROP_FE_BASE_URL}}"