apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  SELFCARE_BROKER_URLS: "{{SELFCARE_BROKER_URLS}}"
  KAFKA_CLIENT_ID: "{{SELFCARE_CONTRACTS_TOPIC_CLIENT_ID}}"
  KAFKA_GROUP_ID: "{{SELFCARE_CONTRACTS_TOPIC_GROUP_ID}}"
  TOPIC_NAME: "{{SELFCARE_CONTRACTS_TOPIC_NAME}}"

  RESET_CONSUMER_OFFSETS: "FALSE"

  INTEROP_PRODUCT: "{{INTEROP_SELFCARE_PRODUCT_NAME}}"
  ALLOWED_ORIGINS: "{{TENANT_ALLOWED_ORIGINS}}"

  TENANT_PROCESS_URL: "http://{{TENANT_PROCESS_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}"

  INTERNAL_JWT_KID: "{{RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{INTERNAL_JWT_SUBJECT}}"
  INTERNAL_JWT_ISSUER: "{{INTERNAL_JWT_ISSUER}}"
  INTERNAL_JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
  INTERNAL_JWT_SECONDS_DURATION: "{{SELFCARE_CONTRACTS_CONSUMER_JWT_DURATION_SECONDS}}"
