#!/bin/bash

# Services Versions
AGREEMENT_MANAGEMENT_IMAGE_VERSION="0.1.4"
AGREEMENT_PROCESS_IMAGE_VERSION="0.1.5"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="0.1.6"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="0.1.4"
AUTHORIZATION_PROCESS_IMAGE_VERSION="0.1.4"
AUTHORIZATION_SERVER_IMAGE_VERSION="0.1.1"
CATALOG_MANAGEMENT_IMAGE_VERSION="0.1.4"
CATALOG_PROCESS_IMAGE_VERSION="0.1.5"
ESERVICE_MOCKUP_IMAGE_VERSION="0.1.2"
PARTY_MANAGEMENT_IMAGE_VERSION="0.1.11-uat-latest"
PARTY_MOCK_REGISTRY_IMAGE_VERSION="0.1.4"
PARTY_PROCESS_IMAGE_VERSION="0.1.8-uat-latest"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="0.1.8-uat-latest"
PURPOSE_MANAGEMENT_IMAGE_VERSION="0.1.4"
PURPOSE_PROCESS_IMAGE_VERSION="0.1.4"
USER_REGISTRY_MANAGEMENT_IMAGE_VERSION="0.1.2"
API_GATEWAY_IMAGE_VERSION="0.1.6"
NOTIFIER_IMAGE_VERSION="0.1.x-latest"

FRONTEND_IMAGE_VERSION="0.1.7"

SPID_LOGIN_MODULE_IMAGE_VERSION="2.1.3"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="0.1.3"
