#!/bin/bash

# Services Versions
AGREEMENT_MANAGEMENT_IMAGE_VERSION="0.1.2"
AGREEMENT_PROCESS_IMAGE_VERSION="0.1.2"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="0.1.2"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="0.1.2"
AUTHORIZATION_PROCESS_IMAGE_VERSION="0.1.2"
CATALOG_MANAGEMENT_IMAGE_VERSION="0.1.2"
CATALOG_PROCESS_IMAGE_VERSION="0.1.2"
ESERVICE_MOCKUP_IMAGE_VERSION="0.1.2"
PARTY_MANAGEMENT_IMAGE_VERSION="0.1.8"
PARTY_MOCK_REGISTRY_IMAGE_VERSION="0.1.3"
PARTY_PROCESS_IMAGE_VERSION="0.1.6"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="0.1.5"
PURPOSE_MANAGEMENT_IMAGE_VERSION="0.1.2"
PURPOSE_PROCESS_IMAGE_VERSION="0.1.2"
USER_REGISTRY_MANAGEMENT_IMAGE_VERSION="0.1.2"
API_GATEWAY_IMAGE_VERSION="0.1.3"

FRONTEND_IMAGE_VERSION="0.1.2"

SPID_LOGIN_MODULE_IMAGE_VERSION="2.1.3"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="0.1.2"
