#!/bin/bash

# Services Versions
AGREEMENT_MANAGEMENT_IMAGE_VERSION="0.1.1-snapshot"
AGREEMENT_PROCESS_IMAGE_VERSION="0.1.1-snapshot"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="0.1.1-snapshot"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="0.1.1-snapshot"
AUTHORIZATION_PROCESS_IMAGE_VERSION="0.1.1-snapshot"
CATALOG_MANAGEMENT_IMAGE_VERSION="0.1.1-snapshot"
CATALOG_PROCESS_IMAGE_VERSION="0.1.1-snapshot"
ESERVICE_MOCKUP_IMAGE_VERSION="0.1.1-snapshot"
PARTY_MANAGEMENT_IMAGE_VERSION="0.1.7-snapshot"
PARTY_MOCK_REGISTRY_IMAGE_VERSION="0.1.0-SNAPSHOT"
PARTY_PROCESS_IMAGE_VERSION="0.1.7-snapshot"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="0.1.3-snapshot"
PURPOSE_MANAGEMENT_IMAGE_VERSION="0.1.1-snapshot"
PURPOSE_PROCESS_IMAGE_VERSION="0.1.1-snapshot"
USER_REGISTRY_MANAGEMENT_IMAGE_VERSION="0.1.1-snapshot"
API_GATEWAY_IMAGE_VERSION="0.1.1-snapshot"

FRONTEND_IMAGE_VERSION="0.1.1-snapshot"

SPID_LOGIN_MODULE_IMAGE_VERSION="2.1.3"
