apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: RATE_LIMITER_MAX_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: RATE_LIMITER_MAX_REQUESTS
            - name: RATE_LIMITER_BURST_PERCENTAGE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: RATE_LIMITER_BURST_PERCENTAGE
            - name: RATE_LIMITER_RATE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: RATE_LIMITER_RATE_INTERVAL
            - name: RATE_LIMITER_REDIS_HOST
              value: "{{REDIS_HOST}}"
            - name: RATE_LIMITER_REDIS_PORT
              value: "{{REDIS_PORT}}"
            - name: RATE_LIMITER_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: RATE_LIMITER_TIMEOUT
