apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  POSTGRES_DB: "persistence_management"
  POSTGRES_SCHEMA: "{{NAMESPACE}}_purpose"
  PERSISTENCE_EVENTS_QUEUE_URL: "{{PERSISTENCE_EVENTS_QUEUE_URL}}"
  AWS_REGION: "{{AWS_REGION}}"
