apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
      annotations:
        digest: {{IMAGE_DIGEST}} # Used to force deployment on same image version but different content
    spec:
      serviceAccountName: {{SERVICE_NAME}}
      terminationGracePeriodSeconds: 31
      containers:
        - name: {{SERVICE_NAME}}
          image: "{{REPOSITORY}}/{{SERVICE_ECR_NAME}}:{{IMAGE_VERSION}}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{BACKEND_SERVICE_PORT}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "{{SERVICE_RESOURCE_CPU}}"
              memory: "{{SERVICE_RESOURCE_MEM}}"
            limits:
              cpu: "{{SERVICE_RESOURCE_CPU}}"
              memory: "{{SERVICE_RESOURCE_MEM}}"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 30; exit 0;"]
          env:
            - name: PORT
              value: "{{BACKEND_SERVICE_PORT}}"
            - name: HOST
              value: "0.0.0.0"
            - name: LOG_LEVEL
              value: info
            - name: EVENTSTORE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-event-store
                  key: EVENTSTORE_DB_HOST
            - name: EVENTSTORE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-event-store
                  key: EVENTSTORE_DB_NAME
            - name: EVENTSTORE_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-event-store
                  key: EVENTSTORE_DB_PORT
            - name: EVENTSTORE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: event-store
                  key: POSTGRES_USR
            - name: EVENTSTORE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-store
                  key: POSTGRES_PSW
            - name: EVENTSTORE_DB_USE_SSL
              value: "true"
            - name: READMODEL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_HOST
            - name: READMODEL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_NAME
            - name: READMODEL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_PORT
            - name: READMODEL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: READONLY_USR
            - name: READMODEL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: READONLY_PSW
            - name: SERVICE_VERSION
              value: {{IMAGE_VERSION}}
            - name: POD_NAME
              valueFrom:             
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_IP
              valueFrom:             
                fieldRef:
                  fieldPath: status.hostIP
            - name: AWS_ROLE_SESSION_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PRODUCER_KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PRODUCER_KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: common-kafka
                  key: KAFKA_BROKERS
            - name: APPLICATION_AUDIT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: common-kafka
                  key: APPLICATION_AUDIT_TOPIC
            - name: FEATURE_FLAG_SQL
              valueFrom:
                configMapKeyRef:
                  name: common-feature-flags
                  key: FEATURE_FLAG_SQL
            - name: FEATURE_FLAG_ADMIN_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: common-feature-flags
                  key: FEATURE_FLAG_ADMIN_CLIENT
            - name: APPLICATION_AUDIT_FALLBACK_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: common-sqs
                  key: APPLICATION_AUDIT_FALLBACK_SQS_URL
            - name: FEATURE_FLAG_APPLICATION_AUDIT_STRICT
              value: "{{FEATURE_FLAG_APPLICATION_AUDIT_STRICT}}"
            - name: READMODEL_SQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST_RO
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_AGREEMENT
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_AGREEMENT
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_ATTRIBUTE
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_ATTRIBUTE
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_CATALOG
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_CATALOG
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_CLIENT
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_CLIENT
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_CLIENT_JWK_KEY
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_DELEGATION
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_DELEGATION
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_ESERVICE_TEMPLATE
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_PRODUCER_JWK_KEY
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_PRODUCER_KEYCHAIN
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_PURPOSE
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_PURPOSE
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_SCHEMA_TENANT
              valueFrom:
                configMapKeyRef:
                  key: DB_SCHEMA_TENANT
                  name: common-read-model-sql
            - name: READMODEL_SQL_DB_USE_SSL
              valueFrom:
                configMapKeyRef:
                  key: DB_USE_SSL
                  name: common-read-model-sql
