apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  CATALOG_PROCESS_URL: "http://{{CATALOG_PROCESS_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}"
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-eservice-descriptors-archiver"
  KAFKA_GROUP_ID: "{{NAMESPACE}}-eservice-descriptors-archiver"
  AGREEMENT_TOPIC: "{{AGREEMENT_TOPIC}}"
  INTERNAL_JWT_KID: {{RSA_KEYS_IDENTIFIERS}}
  INTERNAL_JWT_SECONDS_DURATION: "60"
  INTERNAL_JWT_ISSUER: "dev-refactor.interop.pagopa.it"
  INTERNAL_JWT_SUBJECT: "dev-refactor.interop-attributes-loader"
  INTERNAL_JWT_AUDIENCE: "refactor.dev.interop.pagopa.it/internal"
