apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PRIVACY_NOTICES_LANGS: "{{PRIVACY_NOTICES_LANGS}}"
  PRIVACY_NOTICES_CONTENT_STORAGE_BUCKET: "{{PRIVACY_NOTICES_CONTENT_STORAGE_BUCKET}}"
  PRIVACY_NOTICES_HISTORY_STORAGE_BUCKET: "{{PRIVACY_NOTICES_HISTORY_STORAGE_BUCKET}}"