apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: WELL_KNOWN_URLS
              valueFrom:
                configMapKeyRef:
                  name: common-jwt
                  key: WELL_KNOWN_URLS
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_GROUP_ID
            - name: ATTRIBUTE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ATTRIBUTE_TOPIC


