apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  TENANTS_COLLECTION_NAME: "{{TENANTS_COLLECTION_NAME}}"
  ATTRIBUTES_COLLECTION_NAME: "{{ATTRIBUTES_COLLECTION_NAME}}"
  ESERVICES_COLLECTION_NAME: "{{ESERVICES_COLLECTION_NAME}}"
  DTD_CATALOG_STORAGE_BUCKET: "{{DTD_CATALOG_STORAGE_BUCKET}}"
  DTD_CATALOG_STORAGE_PATH: "{{DTD_CATALOG_STORAGE_PATH}}"
  FILENAME: "catalog.json"