apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  TENANTS_COLLECTION_NAME: "tenants"
  ATTRIBUTES_COLLECTION_NAME: "attributes"
  ESERVICES_COLLECTION_NAME: "eservices"
  DTD_CATALOG_STORAGE_BUCKET: "{{DTD_CATALOG_STORAGE_BUCKET}}"
  DTD_CATALOG_STORAGE_PATH: "{{DTD_CATALOG_STORAGE_PATH}}"
  FILENAME: "catalog.json"