apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
    - port: {{NODEJS_BACKEND_SERVICE_PORT}}
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: {{SERVICE_NAME}}
