apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: CQRS_PROJECTION_DB_HOST
              value: "{{CQRS_PROJECTION_DB_HOST}}"
            - name: CQRS_PROJECTION_DB_PORT
              value: "{{CQRS_PROJECTION_DB_PORT}}"
            - name: CQRS_PROJECTION_DB_NAME
              value: "{{CQRS_PROJECTION_DB_NAME}}"
            - name: CQRS_PROJECTION_DB_USER
              valueFrom:
                secretKeyRef:
                  name: documentdb
                  key: DOCUMENTDB_USR
            - name: CQRS_PROJECTION_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documentdb
                  key: DOCUMENTDB_PSW
