apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: INTERNAL_AUDIENCE_M2M
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: INTERNAL_AUDIENCE_M2M
            
