#!/bin/bash

AGREEMENT_PROCESS_STORAGE_TYPE="S3"
AGREEMENT_PROCESS_STORAGE_CONTAINER="interop-application-documents-dev"
AGREEMENT_PROCESS_STORAGE_ENDPOINT=""
ARCHIVING_PURPOSES_QUEUE_NAME=""

AGREEMENT_PROCESS_RESOURCE_CPU="500m"
AGREEMENT_PROCESS_RESOURCE_MEM="2Gi"
