#!/bin/bash

ATTRIBUTES_LOADER_TOKEN_JWT_ISSUER="interop.pagopa.it"
ATTRIBUTES_LOADER_TOKEN_JWT_SUBJECT="interop-attributes-loader"
ATTRIBUTES_LOADER_TOKEN_JWT_AUDIENCE="interop.pagopa.it/attributes-loader"
ATTRIBUTES_LOADER_TOKEN_JWT_DURATION_SECONDS=3600
