#!/bin/bash

ATTRIBUTES_LOADER_TOKEN_JWT_ISSUER="dev.interop.pagopa.it"
ATTRIBUTES_LOADER_TOKEN_JWT_SUBJECT="dev.interop-attributes-loader"
ATTRIBUTES_LOADER_TOKEN_JWT_DURATION_SECONDS=3600

JOB_ATTRIBUTES_LOADER_RESOURCE_CPU="500"
JOB_ATTRIBUTES_LOADER_RESOURCE_MEM="1Gi"
