#!/bin/bash

INTEROP_JWT_DURATION_SECONDS=99999999
INTEROP_JWT_ISSUER="dev.interop.pagopa.it"

CLIENT_ASSERTION_JWT_AUDIENCE="dev.interop.pagopa.it/client-assertion"

AUTHORIZATION_SERVER_CPU_REQUEST="500m"
AUTHORIZATION_SERVER_MEMORY_REQUEST="2Gi"
AUTHORIZATION_SERVER_CPU_LIMIT="500m"
AUTHORIZATION_SERVER_MEMORY_LIMIT="2Gi"
