#!/bin/bash

INTEROP_JWT_DURATION_SECONDS=99999999
INTEROP_JWT_ISSUER="dev.interop.pagopa.it"

CLIENT_ASSERTION_JWT_AUDIENCE="dev.interop.pagopa.it/client-assertion"

AUTHORIZATION_SERVER_RESOURCE_CPU="500m"
AUTHORIZATION_SERVER_RESOURCE_MEM="2Gi"
