#!/bin/bash

INTEROP_SESSION_TOKEN_DURATION_SECONDS=86400
INTEROP_SESSION_TOKEN_ISSUER="dev.interop.pagopa.it"

SELFCARE_AUDIENCE="api.interop.selfcare.pagopa.it"
SELFCARE_WELL_KNOWN_URL="https://dev.selfcare.pagopa.it/.well-known/jwks.json"

BACKEND_FOR_FRONTEND_RESOURCE_CPU="500m"
BACKEND_FOR_FRONTEND_RESOURCE_MEM="2Gi"
