#!/bin/bash

ARCHIVING_ESERVICES_QUEUE_URL="archived-agreements-for-eservices"
AGREEMENTS_COLLECTION_NAME="agreements"
ESERVICES_COLLECTION_NAME="eservices"

ESERVICE_DESCRIPTORS_ARCHIVER_RESOURCE_CPU="500m"
ESERVICE_DESCRIPTORS_ARCHIVER_RESOURCE_MEM="1Gi"

ESERVICE_DESCRIPTORS_ARCHIVERJWT_ISSUER="dev.interop.pagopa.it"
ESERVICE_DESCRIPTORS_ARCHIVERJWT_SUBJECT="dev.interop-eservice-descriptors-archiver"
ESERVICE_DESCRIPTORS_ARCHIVERJWT_DURATION_SECONDS=3600