#!/bin/bash

INTERFACES_CONTAINER="interop-application-documents-dev"

METRICS_CONTAINER="interop-platform-metrics-dev"
METRICS_STORAGE_PATH="pa-digitale"

ESERVICES_COLLECTION_NAME="eservices"
TENANTS_COLLECTION_NAME="tenants"

JOB_METRICS_REPORT_GENERATOR_RESOURCE_CPU="500m"
JOB_METRICS_REPORT_GENERATOR_RESOURCE_MEM="1Gi"