#!/bin/bash

REPORTS_CONTAINER="interop-platform-metrics-dev"
AGREEMENTS_CSV_STORAGE_PATH="agreements/csv"
AGREEMENTS_JSON_STORAGE_PATH="agreements/json"

TENANTS_COLLECTION_NAME="tenants"
PURPOSES_COLLECTION_NAME="purposes"
AGREEMENTS_COLLECTION_NAME="agreements"

JOB_METRICS_REPORT_GENERATOR_RESOURCE_CPU="500m"
JOB_METRICS_REPORT_GENERATOR_RESOURCE_MEM="1Gi"