#!/bin/bash

# Services Versions
AGREEMENT_MANAGEMENT_IMAGE_VERSION="1.0.x-latest"
AGREEMENT_PROCESS_IMAGE_VERSION="1.0.x-latest"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="1.0.x-latest"
ATTRIBUTE_REGISTRY_PROCESS_IMAGE_VERSION="1.0.x-latest"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="1.0.x-latest"
AUTHORIZATION_PROCESS_IMAGE_VERSION="1.0.x-latest"
AUTHORIZATION_SERVER_IMAGE_VERSION="1.0.x-latest"
CATALOG_MANAGEMENT_IMAGE_VERSION="1.0.x-latest"
CATALOG_PROCESS_IMAGE_VERSION="1.0.x-latest"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="1.0.x-latest"
PURPOSE_MANAGEMENT_IMAGE_VERSION="1.0.x-latest"
PURPOSE_PROCESS_IMAGE_VERSION="1.0.x-latest"
TENANT_MANAGEMENT_IMAGE_VERSION="1.0.x-latest"
TENANT_PROCESS_IMAGE_VERSION="1.0.x-latest"
API_GATEWAY_IMAGE_VERSION="1.0.x-latest"
BACKEND_FOR_FRONTEND_IMAGE_VERSION="1.0.x-latest"
NOTIFIER_IMAGE_VERSION="1.0.x-latest"

FRONTEND_IMAGE_VERSION="dev-latest"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="1.0.x-latest"
JOB_DETAILS_PERSISTER_IMAGE_VERSION="1.0.x-latest"
JOB_TENANTS_CERTIFIED_ATTRIBUTES_UPDATER_IMAGE_VERSION="1.0.x-latest"
JOB_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.x-latest"
JOB_PADIGITALE_REPORT_GENERATOR_IMAGE_VERSION="1.0.x-latest"
JOB_DASHBOARD_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.x-latest"
