apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  INTEROP_RSA_PRIVATE_VAULT_PATH: "secret/data/interop/keys/rsa/jwk/private"
  INTEROP_JWT_DURATION: "{{INTEROP_JWT_DURATION}}"
  INTEROP_JWT_ISSUER: "{{INTEROP_JWT_ISSUER}}"