apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  EC_KEYS_IDENTIFIERS: "{{EC_KEYS_IDENTIFIERS}}"
  RSA_KEYS_IDENTIFIERS: "{{RSA_KEYS_IDENTIFIERS}}"
  VAULT_SIGNATURE_ROUTE: "{{VAULT_SIGNATURE_ROUTE}}"

  GENERATED_JWT_DURATION_SECONDS: "{{INTEROP_SESSION_TOKEN_DURATION_SECONDS}}"
  GENERATED_JWT_ISSUER: "{{INTEROP_SESSION_TOKEN_ISSUER}}"
  GENERATED_JWT_AUDIENCE: "{{UI_JWT_AUDIENCE}}"

  ACCEPTED_AUDIENCES: "{{UI_JWT_AUDIENCE}}"
