apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ACCEPTED_AUDIENCES
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: VAULT_ADDR
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: VAULT_TOKEN
            - name: EC_KEYS_IDENTIFIERS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: EC_KEYS_IDENTIFIERS
            - name: RSA_KEYS_IDENTIFIERS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: RSA_KEYS_IDENTIFIERS
            - name: VAULT_SIGNATURE_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: VAULT_SIGNATURE_ROUTE
            - name: GENERATED_JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: GENERATED_JWT_AUDIENCE
            - name: GENERATED_JWT_DURATION_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: GENERATED_JWT_DURATION_SECONDS
            - name: GENERATED_JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: GENERATED_JWT_ISSUER