apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  config.yaml: |-
    ---
    # CONFIGURAZIONE IDENTITY PROVIDER

    # Hostname da usare per generare l'entityID dell'IdP e gli URL degli endpoint
    # SAML indicati nel metadata dell'IdP
    hostname: "localhost"
    base_url: "https://{{SERVICE_NAME}}:8088"

    # Chiave e certificato necessari per la firma dei messaggi SAML
    key_file: "conf/idp.key"
    cert_file: "conf/idp.crt"


    # CONFIGURAZIONE SERVICE PROVIDER

    # Si possono configurare più Service Provider. Per leggere i metadati da un 
    # file .xml è sufficiente inserirne il path sotto "local"; per leggerli da 
    # un URL remoto bisogna invece inserirlo sotto "remote" (insieme al path di
    # una copia locale del certificato del Service Provider, che per sicurezza 
    # deve coincidere con quello presente nei metadati).
    # cfr. https://pysaml2.readthedocs.io/en/latest/howto/config.html#metadata
    metadata:
      remote:
        - "http://{{SPID_LOGIN_URL}}:9090/metadata"

    # CONFIGURAZIONE TESTENV WEB SERVER

    # Abilita (true) o disabilita (false) la modalità debug
    debug: true

    # Indirizzo IP dell'interfaccia su cui esporre il server e porta
    # (0.0.0.0 per ascoltare su tutte le interfacce)
    host: 0.0.0.0
    port: 8088

    # Abilita (true) o disabilita (false) la modalità HTTPS per l'IdP
    https: true

    # Se si abilita HTTPS è necessario specificare chiave e certificato
    # (indipendenti da chiave e certificato SAML)
    https_key_file: "./certs/certificate.pem"
    https_cert_file: "./certs/certificate.crt"

    # Endpoint del server IdP (path relativi)
    endpoints:
      single_sign_on_service: "/sso"
      single_logout_service: "/slo"

  users.json: |-
    {
      "carla.rossi": {
        "sp": null,
        "attrs": {
            "fiscalNumber": "ISPXNB32R82Y766D",
            "name": "Carla",
            "gender": "F",
            "familyName": "Rossi",
            "dateOfBirth": "2000-12-12",
            "email": "carla.rossi@test.pagopa.it",
            "spidCode": "7b09078d-989b-6e6d-87b9-aab53efd714f",
            "mobilePhone": "333333333",
            "address": "Via Roma 1, Roma"
        },
        "pwd": "test"
      },
      "mario.rossi": {
        "sp": null,
        "attrs": {
            "fiscalNumber": "GDNNWA12H81Y874F",
            "name": "Mario",
            "gender": "M",
            "familyName": "Rossi",
            "dateOfBirth": "1991-12-12",
            "email": "mario.rossi@test.pagopa.it",
            "spidCode": "d4b9f692-a0f2-1100-7bb6-8650c02d75d5",
            "mobilePhone": "333333334",
            "address": "Via Roma 2, Roma"
        },
        "pwd": "test"
      }
    }
  