apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: italia/spid-testenv2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/app/conf/config.yaml"
            - name: users
              mountPath: "/app/conf/users.json"
              subPath: "users.json"
            - name: idp-http-certs
              mountPath: "/app/certs"
              readOnly: true
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: {{SERVICE_NAME}}
                  items:
                    - key: config.yaml
                      path: config.yaml
        - name: users
          persistentVolumeClaim:
            claimName: {{SERVICE_NAME}}-users
        - name: conf
          emptyDir: {}
        - name: idp-http-certs
          secret:
            secretName: idp-http-certs
        