apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: italia/spid-testenv2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/app/conf/config.yaml"
              subPath: "config.yaml"
            - name: users
              mountPath: "/app/conf/users.json"
              subPath: "users.json"
            - name: idp-http-certs
              mountPath: "/app/certs"
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "15m"
            limits:
              memory: "512Mi"
              cpu: "100m"
      initContainers:
        # Used to initialize users file if not already created
        # Note: A better solution is to use dataSourceRef on pvc, but it is available on k8s 1.22+
        - name: rw-conf-directory
          image: busybox:1.34
          command: ['sh', '-c', "cp -n /temp/app/conf/users.json /app/conf/users.json"]
          volumeMounts:
            - name: users-tmp
              mountPath: "/temp/app/conf/users.json"
              subPath: "users.json"
            - name: users
              mountPath: "/app/conf"
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: {{SERVICE_NAME}}
            items:
              - key: config.yaml
                path: config.yaml
        - name: users-tmp
          configMap:
            name: {{SERVICE_NAME}}
            items:
              - key: users.json
                path: users.json
        - name: users
          persistentVolumeClaim:
            claimName: {{SERVICE_NAME}}-users
        - name: idp-http-certs
          secret:
            secretName: idp-http-certs
        