kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}-users
  namespace: {{NAMESPACE}}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem