apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  EC_KEYS_IDENTIFIERS: "{{EC_KEYS_IDENTIFIERS}}"
  RSA_KEYS_IDENTIFIERS: "{{RSA_KEYS_IDENTIFIERS}}"
  
  GENERATED_M2M_JWT_AUDIENCE: "{{M2M_JWT_AUDIENCE}}"
  GENERATED_JWT_ISSUER: "{{INTEROP_JWT_ISSUER}}"
  GENERATED_M2M_JWT_DURATION_SECONDS: "{{INTEROP_JWT_DURATION_SECONDS}}"

  INTERNAL_JWT_ISSUER: "{{INTERNAL_JWT_ISSUER}}"
  INTERNAL_JWT_SUBJECT: "{{INTERNAL_JWT_SUBJECT}}"
  INTERNAL_JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
  INTERNAL_JWT_DURATION_SECONDS: "{{INTERNAL_JWT_DURATION_SECONDS}}"

  CLIENT_ASSERTION_JWT_AUDIENCE: "{{CLIENT_ASSERTION_JWT_AUDIENCE}}"

  GENERATED_JWT_QUEUE_NAME: "generated-jwt"

  RATE_LIMITER_MAX_REQUESTS: "{{AUTH_SERVER_RATE_LIMITER_MAX_REQUESTS}}"
  RATE_LIMITER_BURST_PERCENTAGE: "{{AUTH_SERVER_RATE_LIMITER_BURST_PERCENTAGE}}"
  RATE_LIMITER_RATE_INTERVAL: "{{AUTH_SERVER_RATE_LIMITER_RATE_INTERVAL}}"
  RATE_LIMITER_TIMEOUT: "{{AUTH_SERVER_RATE_LIMITER_TIMEOUT}}"

  JWT_FALLBACK_BUCKET: "{{JWT_FALLBACK_BUCKET}}"