apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: {{BACKEND_SERVICE_PORT}}
    alb.ingress.kubernetes.io/healthcheck-path: /{{AUTHORIZATION_SERVER_APPLICATION_PATH}}/status

