apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  TENANTS_COLLECTION_NAME: "tenants"
  ATTRIBUTES_COLLECTION_NAME: "attributes"
  ESERVICES_COLLECTION_NAME: "eservices"
  S3_BUCKET: "{{DTD_CATALOG_STORAGE_BUCKET}}"
  DTD_CATALOG_STORAGE_PATH: "{{DTD_CATALOG_STORAGE_PATH}}"
  DTD_CATALOG_JSON_FILENAME: "eservice_a_catalogo.json"
  DTD_CATALOG_CSV_FILENAME: "eservice_a_catalogo.csv"
  DTD_TENANTS_CSV_FILENAME: "aderenti.csv"
  DTD_TENANTS_JSON_FILENAME: "aderenti.json"
  GITHUB_REPO: "pdnd-opendata"
  GITHUB_REPO_OWNER: "italia"