apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PDND_INTEROP_KEYS_VALUT_PATH: "secret/data/pdnd-interop/keys"
  PARTY_REGISTRY_PROXY_URL: "http://{{PARTY_REGISTRY_PROXY_SERVICE_NAME}}:8088/{{PARTY_REGISTRY_PROXY_SERVICE_NAME}}/{{PARTY_REGISTRY_PROXY_INTERFACE_VERSION}}"
  USER_REGISTRY_MANAGEMENT_URL: "{{USER_REGISTRY_MANAGEMENT_URL}}"
  
