apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PARTY_REGISTRY_PROXY_URL: "http://{{PARTY_REGISTRY_PROXY_SERVICE_NAME}}:8088/{{PARTY_REGISTRY_PROXY_APPLICATION_PATH}}/{{PARTY_REGISTRY_PROXY_INTERFACE_VERSION}}"
  USER_REGISTRY_MANAGEMENT_URL: "{{USER_REGISTRY_MANAGEMENT_URL}}"
  
