apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
      annotations:
        digest: {{IMAGE_DIGEST}} # Used to force deployment on same image version but different content
    spec:
      template:
        metadata:
          labels:
            app: {{SERVICE_NAME}}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{SERVICE_NAME}}
          containers:
            - name: {{SERVICE_NAME}}
              image: {{REPOSITORY}}/{{SERVICE_NAME}}:{{JOB_CERTIFIED_MAIL_IMAGE_VERSION}}
              imagePullPolicy: Always
              command: ["bin/{{SERVICE_NAME}}"]
              args: ["-Dconfig.override_with_env_vars=true"]
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: PEC_QUEUE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: PEC_QUEUE_URL
                - name: SMTP_SENDER
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: SMTP_SENDER
                - name: SMTP_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: SMTP_ADDRESS
                - name: SMTP_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: SMTP_PORT
                - name: WITH_SSL
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: WITH_SSL
                - name: SMTP_USER
                  valueFrom:
                    secretKeyRef:
                      name: smtp-certified
                      key: SMTP_USER
                - name: SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: smtp-certified
                      key: SMTP_PASSWORD     
              resources:
                requests:
                  cpu: "{{SERVICE_RESOURCE_CPU}}"
                  memory: "{{SERVICE_RESOURCE_MEM}}"
                limits:
                  cpu: "{{SERVICE_RESOURCE_CPU}}"
                  memory: "{{SERVICE_RESOURCE_MEM}}"
