apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PARTY_MANAGEMENT_STORAGE_TYPE: ""
  PARTY_MANAGEMENT_STORAGE_CONTAINER: ""
  PARTY_MANAGEMENT_STORAGE_ENDPOINT: ""
  POSTGRES_HOST: ""
