apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_TYPE
            - name: STORAGE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_CONTAINER
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_ENDPOINT
            - name: STORAGE_CREDENTIAL_ID
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: STORAGE_USR
            - name: STORAGE_CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: STORAGE_PSW
            - name: TOKEN_VALIDITY_HOURS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: TOKEN_VALIDITY_HOURS
            - name: ENABLED_PROJECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ENABLED_PROJECTIONS