apiVersion: v1
kind: ConfigMap
metadata:
  name: common-services-urls
  namespace: {{NAMESPACE}}
data:
  AUTHORIZATION_MANAGEMENT_URL: {{AUTHORIZATION_MANAGEMENT_URL}}
  DELEGATION_PROCESS_URL: {{DELEGATION_PROCESS_URL}}
  AGREEMENT_PROCESS_URL: {{AGREEMENT_PROCESS_URL}}
  PURPOSE_PROCESS_URL: {{PURPOSE_PROCESS_URL}}
