apiVersion: v1
kind: ConfigMap
metadata:
  name: common-token-generation-read-model
  namespace: {{NAMESPACE}}
data:
  TOKEN_GENERATION_READMODEL_TABLE_NAME_PLATFORM: {{TOKEN_GENERATION_READMODEL_TABLE_NAME_PLATFORM}}
  TOKEN_GENERATION_READMODEL_TABLE_NAME_TOKEN_GENERATION: {{TOKEN_GENERATION_READMODEL_TABLE_NAME_TOKEN_GENERATION}}
