apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-eservice-template-updater"
  KAFKA_GROUP_ID: "{{NAMESPACE}}-eservice-template-updater"

  ESERVICE_DOCUMENTS_CONTAINER: "{{CATALOG_PROCESS_STORAGE_CONTAINER}}"
  ESERVICE_DOCUMENTS_PATHS: "{{CATALOG_PROCESS_ESERVICE_DOCUMENTS_PATH}}"

  INTERNAL_JWT_KID: "{{RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{INTERNAL_JWT_SUBJECT}}"
  INTERNAL_JWT_ISSUER: "{{INTERNAL_JWT_ISSUER}}"
  INTERNAL_JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
  INTERNAL_JWT_SECONDS_DURATION: "{{INTERNAL_JWT_DURATION_SECONDS}}"
