apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-authorization-process"
  AUDIT_FALLBACK_S3_BUCKET: "{{JWT_FALLBACK_BUCKET}}"
  GENERATED_INTEROP_TOKEN_KID: "{{RSA_KEYS_IDENTIFIERS}}"
  GENERATED_INTEROP_TOKEN_ISSUER: "{{INTEROP_JWT_ISSUER}}"
  GENERATED_INTEROP_TOKEN_M2M_AUDIENCE: "{{M2M_JWT_AUDIENCE}}"
  GENERATED_INTEROP_TOKEN_M2M_DURATION_SECONDS: "{{INTEROP_JWT_DURATION_SECONDS}}"

  CLIENT_ASSERTION_JWT_AUDIENCE: "{{CLIENT_ASSERTION_JWT_AUDIENCE}}"

  RATE_LIMITER_MAX_REQUESTS: "{{AUTH_SERVER_RATE_LIMITER_MAX_REQUESTS}}"
  RATE_LIMITER_BURST_PERCENTAGE: "{{AUTH_SERVER_RATE_LIMITER_BURST_PERCENTAGE}}"
  RATE_LIMITER_RATE_INTERVAL_MILLIS: "{{AUTH_SERVER_RATE_LIMITER_RATE_INTERVAL_MILLIS}}"
  RATE_LIMITER_TIMEOUT_MILLIS: "{{AUTH_SERVER_BFF_RATE_LIMITER_TIMEOUT_MILLIS}}"
