apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  EVENTSTORE_DB_SCHEMA: "{{NAMESPACE}}_attribute_registry"
  PRODUCER_ALLOWED_ORIGINS: "{{PRODUCER_ALLOWED_ORIGINS}}"
