apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
          - name: EVENTSTORE_DB_SCHEMA
            valueFrom:
              configMapKeyRef:
                name: {{SERVICE_NAME}}
                key: EVENTSTORE_DB_SCHEMA
          - name: WELL_KNOWN_URLS
            valueFrom:
              configMapKeyRef:
                name: common-jwt
                key: WELL_KNOWN_URLS
          - name: PRODUCER_ALLOWED_ORIGINS
            valueFrom:
              configMapKeyRef:
                name: {{SERVICE_NAME}}
                key: PRODUCER_ALLOWED_ORIGINS
          - name: ACCEPTED_AUDIENCES
            valueFrom:
              configMapKeyRef:
                name: {{SERVICE_NAME}}
                key: ACCEPTED_AUDIENCES
