apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  EVENTSTORE_DB_USE_SSL: "true"
  EVENTSTORE_DB_SCHEMA: "{{NAMESPACE}}_catalog"
  ESERVICE_DOCUMENTS_PATH: ""
  S3_BUCKET: "{{CATALOG_PROCESS_STORAGE_CONTAINER}}"
