apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  MOCK_FILE_MANAGER: "true"
  EVENTSTORE_DB_USE_SSL: "true"
  EVENTSTORE_DB_SCHEMA: "catalog"
  ESERVICE_DOCUMENTS_PATH: ""
  STORAGE_CONTAINER: ""
