apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  ACCEPTED_AUDIENCES: "{{M2M_JWT_AUDIENCE}}"
  PARTY_MANAGEMENT_URL: "{{PARTY_MANAGEMENT_URL}}"
  TENANT_PROCESS_URL: "http://{{TENANT_PROCESS_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{TENANT_PROCESS_APPLICATION_PATH}}/{{TENANT_PROCESS_INTERFACE_VERSION}}"
