apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  INTEROP_KEYS_VAULT_PATH: "secret/data/interop/keys"
  INTEROP_JWT_DURATION: "{{INTEROP_JWT_DURATION}}"