apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  ACCEPTED_AUDIENCES: "{{UI_JWT_AUDIENCE}},{{M2M_JWT_AUDIENCE}},{{INTERNAL_JWT_AUDIENCE}}"
  AGREEMENT_PROCESS_URL: "http://{{AGREEMENT_PROCESS_SERVICE_NAME}}:{{SCALA_BACKEND_SERVICE_PORT}}/{{AGREEMENT_PROCESS_APPLICATION_PATH}}/{{AGREEMENT_PROCESS_INTERFACE_VERSION}}"
