#!/bin/bash

ATTRIBUTES_LOADER_TOKEN_JWT_ISSUER="uat.interop.pagopa.it"
ATTRIBUTES_LOADER_TOKEN_JWT_SUBJECT="uat.interop-attributes-loader"
ATTRIBUTES_LOADER_TOKEN_JWT_DURATION_SECONDS=3600

JOB_ATTRIBUTES_LOADER_RESOURCE_CPU="500m"
JOB_ATTRIBUTES_LOADER_RESOURCE_MEM="1Gi"
