export CANARY_INGRESS_NAME="interop-be-authorization-server-canary"
export CANARY_INGRESS_GROUP_NAME="interop-be"
export CANARY_INGRESS_SCHEME="internal"
export CANARY_INGRESS_TARGET_TYPE="ip"
export CANARY_ANNOTATION_ACTION_NAME="auth-server-canary"

export CANARY_ORIGINAL_SERVICE_NAME="interop-be-authorization-server"
export CANARY_ORIGINAL_SERVICE_PORT=$BACKEND_SERVICE_PORT
export CANARY_ORIGINAL_SERVICE_WEIGHT=90
export CANARY_NEW_SERVICE_NAME="interop-be-authorization-server-node"
export CANARY_NEW_SERVICE_PORT=$BACKEND_SERVICE_PORT
export CANARY_NEW_SERVICE_WEIGHT=10

export CANARY_SERVICE_PATH="$AUTHORIZATION_SERVER_APPLICATION_PATH"
