#!/bin/bash

IVASS_CERTIFIED_ATTRIBUTES_IMPORTER_JWT_DURATION_SECONDS="1800"
IVASS_TENANT_ID="ba3407d7-16cf-4bef-bafc-7f9105889cf7"
IVASS_CERTIFIED_ATTRIBUTES_RECORDS_PROCESS_BATCH_SIZE="100"
IVASS_SOURCE_URL="https://infostat-ivass.bancaditalia.it/RIGAInquiry-public/getAreaDownloadExport.do?referenceDate=&product=VFLUSSO_IMPRESE&language=IT&exportType=CSV&username=OBLIXANONYMOUS&isCompressed=S"
IVASS_HISTORY_BUCKET_NAME="interop-ivass-test-es1"

JOB_IVASS_CERTIFIED_ATTRIBUTES_IMPORTER_RESOURCE_CPU="1"
JOB_IVASS_CERTIFIED_ATTRIBUTES_IMPORTER_RESOURCE_MEM="2Gi"
