apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_DB
            - name: POSTGRES_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_SCHEMA
            - name: POSTGRES_USR
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USR
            - name: POSTGRES_PSW
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PSW
            - name: STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_TYPE
            - name: STORAGE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_CONTAINER
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_ENDPOINT
            - name: STORAGE_CREDENTIAL_ID
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: STORAGE_USR
            - name: STORAGE_CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: STORAGE_PSW
            - name: WELL_KNOWN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: WELL_KNOWN_URL
