apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  TENANTS_COLLECTION_NAME: "{{TENANTS_COLLECTION_NAME}}"
  PURPOSES_COLLECTION_NAME: "{{PURPOSES_COLLECTION_NAME}}"
  ESERVICES_COLLECTION_NAME: "{{ESERVICES_COLLECTION_NAME}}"
  ATTRIBUTES_COLLECTION_NAME: "{{ATTRIBUTES_COLLECTION_NAME}}"
  AGREEMENTS_COLLECTION_NAME: "{{AGREEMENTS_COLLECTION_NAME}}"
  STORAGE_BUCKET: "{{STORAGE_BUCKET}}"
  FILENAME: "{{FILENAME}}"
  ATHENA_TOKENS_TABLE_NAME: "{{ATHENA_TOKENS_TABLE_NAME}}"
  ATHENA_OUTPUT_BUCKET: "{{ATHENA_OUTPUT_BUCKET}}"

  GITHUB_REPO: "{{DTD_PDND_OPENDATA_REPOSITORY}}"
  GITHUB_REPO_OWNER: "{{DTD_REPOSITORY_OWNER}}"