apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
      annotations:
        digest: {{IMAGE_DIGEST}} # Used to force deployment on same image version but different content
    spec:
      serviceAccountName: {{SERVICE_NAME}}
      containers:
        - name: {{SERVICE_NAME}}
          image: "{{REPOSITORY}}/{{SERVICE_NAME}}:{{IMAGE_VERSION}}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "{{SERVICE_RESOURCE_CPU}}"
              memory: "{{SERVICE_RESOURCE_MEM}}"
            limits:
              cpu: "{{SERVICE_RESOURCE_CPU}}"
              memory: "{{SERVICE_RESOURCE_MEM}}"
          env:
            - name: LOG_LEVEL
              value: info
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: common-kafka
                  key: KAFKA_BROKERS



