apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  CATALOG_PROCESS_URL: "http://{{CATALOG_PROCESS_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}"
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-eservice-descriptors-archiver"
  KAFKA_GROUP_ID: "{{NAMESPACE}}-eservice-descriptors-archiver"
  INTERNAL_JWT_KID: {{RSA_KEYS_IDENTIFIERS}}
  INTERNAL_JWT_SECONDS_DURATION: "{{ESERVICE_DESCRIPTORS_ARCHIVER_JWT_DURATION_SECONDS}}"
  INTERNAL_JWT_ISSUER: "{{INTERNAL_JWT_ISSUER}}"
  INTERNAL_JWT_SUBJECT: "{{ESERVICE_DESCRIPTORS_ARCHIVER_JWT_SUBJECT}}"
  INTERNAL_JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
