apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          livenessProbe:
            httpGet:
              path: "/{{API_GATEWAY_APPLICATION_PATH}}/{{API_GATEWAY_INTERFACE_VERSION}}/status"
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/{{API_GATEWAY_APPLICATION_PATH}}/{{API_GATEWAY_INTERFACE_VERSION}}/status"
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ACCEPTED_AUDIENCES
            - name: AGREEMENT_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_PROCESS_URL
            - name: AUTHORIZATION_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AUTHORIZATION_PROCESS_URL
            - name: CATALOG_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: CATALOG_PROCESS_URL
            - name: PARTY_REGISTRY_PROXY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_REGISTRY_PROXY_URL
            - name: ATTRIBUTE_REGISTRY_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ATTRIBUTE_REGISTRY_PROCESS_URL
            - name: PURPOSE_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PURPOSE_PROCESS_URL
            - name: TENANT_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: TENANT_PROCESS_URL
            - name: NOTIFIER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: NOTIFIER_URL
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: BASE_URL
            - name: API_GATEWAY_INTERFACE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: API_GATEWAY_INTERFACE_VERSION
            - name: WELL_KNOWN_URLS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: WELL_KNOWN_URLS
            - name: READMODEL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_HOST
            - name: READMODEL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_NAME
            - name: READMODEL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: READONLY_USR
            - name: READMODEL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: READONLY_PSW
            - name: READMODEL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_PORT