apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ACCEPTED_AUDIENCES
            - name: AGREEMENT_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_PROCESS_URL
            - name: AUTHORIZATION_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AUTHORIZATION_PROCESS_URL
            - name: CATALOG_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: CATALOG_PROCESS_URL
            - name: PARTY_REGISTRY_PROXY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_REGISTRY_PROXY_URL
            - name: ATTRIBUTE_REGISTRY_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ATTRIBUTE_REGISTRY_PROCESS_URL
            - name: PURPOSE_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PURPOSE_PROCESS_URL
            - name: TENANT_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: TENANT_PROCESS_URL
            - name: NOTIFIER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: NOTIFIER_URL
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: BASE_URL
            - name: WELL_KNOWN_URLS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: WELL_KNOWN_URLS
            - name: RATE_LIMITER_RATE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: RATE_LIMITER_RATE_INTERVAL
            - name: RATE_LIMITER_TIMEOUT
              valueFrom:
                configMapKeyRef::
                  name:  {{SERVICE_NAME}}
                  key: RATE_LIMITER_TIMEOUT
            - name: READMODEL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_HOST
            - name: READMODEL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_NAME
            - name: READMODEL_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_USERNAME           
            - name: READMODEL_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_PASSWORD
            - name: READMODEL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-read-model
                  key: READMODEL_DB_PORT