apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  INTERFACES_CONTAINER: "{{INTERFACES_CONTAINER}}"
  METRICS_CONTAINER: "{{METRICS_CONTAINER}}"
  METRICS_STORAGE_PATH: "{{METRICS_STORAGE_PATH}}"
  ESERVICES_COLLECTION_NAME: "{{ESERVICES_COLLECTION_NAME}}"
  TENANTS_COLLECTION_NAME: "{{TENANTS_COLLECTION_NAME}}"