apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  AGREEMENTS_CONTAINER: "{{REPORTS_CONTAINER}}"
  AGREEMENTS_CSV_STORAGE_PATH: "{{AGREEMENTS_CSV_STORAGE_PATH}}"
  AGREEMENTS_JSON_STORAGE_PATH: "{{AGREEMENTS_JSON_STORAGE_PATH}}"
  TENANTS_COLLECTION_NAME: "{{TENANTS_COLLECTION_NAME}}"
  PURPOSES_COLLECTION_NAME: "{{PURPOSES_COLLECTION_NAME}}"
  AGREEMENTS_COLLECTION_NAME: "{{AGREEMENTS_COLLECTION_NAME}}"