apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  schedule: "0 8 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
      annotations:
        digest: {{IMAGE_DIGEST}} # Used to force deployment on same image version but different content
    spec:
      template:
        metadata:
          labels:
            app: {{SERVICE_NAME}}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{SERVICE_NAME}}
          containers:
            - name: {{SERVICE_NAME}}
              image: {{REPOSITORY}}/{{SERVICE_NAME}}:{{JOB_METRICS_REPORT_GENERATOR_IMAGE_VERSION}}
              imagePullPolicy: Always
              command: ["bin/{{SERVICE_NAME}}"]
              args: ["-Dconfig.override_with_env_vars=true"]
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: READ_MODEL_DB_HOST
                  value: "{{READ_MODEL_DB_HOST}}"
                - name: READ_MODEL_DB_PORT
                  value: "{{READ_MODEL_DB_PORT}}"
                - name: READ_MODEL_DB_NAME
                  value: "{{READ_MODEL_DB_NAME}}"
                - name: ESERVICES_COLLECTION_NAME
                  valueFrom:
                      configMapKeyRef:
                        name: {{SERVICE_NAME}}
                        key: ESERVICES_COLLECTION_NAME
                - name: TENANTS_COLLECTION_NAME
                  valueFrom:
                      configMapKeyRef:
                        name: {{SERVICE_NAME}}
                        key: TENANTS_COLLECTION_NAME
                - name: READ_MODEL_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: documentdb
                      key: READONLY_USR
                - name: READ_MODEL_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: documentdb
                      key: READONLY_PSW
              resources:
                requests:
                  cpu: "{{SERVICE_RESOURCE_CPU}}"
                  memory: "{{SERVICE_RESOURCE_MEM}}"
                limits:
                  cpu: "{{SERVICE_RESOURCE_CPU}}"
                  memory: "{{SERVICE_RESOURCE_MEM}}"
