apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_GROUP_ID
            - name: AGREEMENT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: common-kafka
                  key: AGREEMENT_TOPIC
            - name: AGREEMENT_EMAIL_SENDER
              valueFrom:
                secretKeyRef:
                  name: smtp-certified
                  key: PEC_SMTP_SENDER
            - name: SMTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: SMTP_ADDRESS
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: SMTP_PORT
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-certified
                  key: PEC_SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-certified
                  key: PEC_SMTP_PASSWORD
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: SMTP_SECURE
