apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PEC_QUEUE_URL: "certified-mail.fifo"
  PEC_SMTP_ADDRESS: "{{PEC_SMTP_ADDRESS}}"
  PEC_SMTP_PORT: "{{PEC_SMTP_PORT}}"
  PEC_WITH_SSL: "{{PEC_WITH_SSL}}"
