apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  # Managements Endpoints
  AGREEMENT_MANAGEMENT_URL: "{{AGREEMENT_MANAGEMENT_SERVICE_NAME}}/{{AGREEMENT_MANAGEMENT_INTERFACE_VERSION}}"
  ATTRIBUTE_REGISTRY_MANAGEMENT_URL: "{{ATTRIBUTE_REGISTRY_MANAGEMENT_SERVICE_NAME}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_INTERFACE_VERSION}}"
  CATALOG_MANAGEMENT_URL: "{{CATALOG_MANAGEMENT_SERVICE_NAME}}/{{CATALOG_MANAGEMENT_INTERFACE_VERSION}}"
  PARTY_MANAGEMENT_URL: "{{PARTY_MANAGEMENT_SERVICE_NAME}}/{{PARTY_MANAGEMENT_INTERFACE_VERSION}}"
  POSTGRES_HOST: "{{POSTGRES_HOST}}"