apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  AUTHORIZATION_MANAGEMENT_URL: "http://{{AUTHORIZATION_MANAGEMENT_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{AUTHORIZATION_MANAGEMENT_APPLICATION_PATH}}/{{AUTHORIZATION_MANAGEMENT_INTERFACE_VERSION}}"
  NOTIFIER_URL: "http://{{NOTIFIER_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{NOTIFIER_APPLICATION_PATH}}/{{NOTIFIER_INTERFACE_VERSION}}"

  WELL_KNOWN_URLS: "{{WELL_KNOWN_URLS}}"

  ENABLED_PROJECTIONS: "{{ENABLED_PROJECTIONS}}"
  DEV_ENDPOINTS_ENABLED: "{{DEV_ENDPOINTS_ENABLED}}"
