apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  # Managements Endpoints
  AGREEMENT_MANAGEMENT_URL: "http://{{AGREEMENT_MANAGEMENT_SERVICE_NAME}}:8088/{{AGREEMENT_MANAGEMENT_APPLICATION_PATH}}/{{AGREEMENT_MANAGEMENT_INTERFACE_VERSION}}"
  ATTRIBUTE_REGISTRY_MANAGEMENT_URL: "http://{{ATTRIBUTE_REGISTRY_MANAGEMENT_SERVICE_NAME}}:8088/{{ATTRIBUTE_REGISTRY_MANAGEMENT_APPLICATION_PATH}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_INTERFACE_VERSION}}"
  AUTHORIZATION_MANAGEMENT_URL: "http://{{AUTHORIZATION_MANAGEMENT_SERVICE_NAME}}:8088/{{AUTHORIZATION_MANAGEMENT_APPLICATION_PATH}}/{{AUTHORIZATION_MANAGEMENT_INTERFACE_VERSION}}"
  CATALOG_MANAGEMENT_URL: "http://{{CATALOG_MANAGEMENT_SERVICE_NAME}}:8088/{{CATALOG_MANAGEMENT_APPLICATION_PATH}}/{{CATALOG_MANAGEMENT_INTERFACE_VERSION}}"
  PARTY_MANAGEMENT_URL: "http://{{PARTY_MANAGEMENT_SERVICE_NAME}}:8088/{{PARTY_MANAGEMENT_APPLICATION_PATH}}/{{PARTY_MANAGEMENT_INTERFACE_VERSION}}"
  PURPOSE_MANAGEMENT_URL: "http://{{PURPOSE_MANAGEMENT_SERVICE_NAME}}:8088/{{PURPOSE_MANAGEMENT_APPLICATION_PATH}}/{{PURPOSE_MANAGEMENT_INTERFACE_VERSION}}"
  
  POSTGRES_HOST: "{{POSTGRES_HOST}}"
  POSTGRES_PORT: "{{POSTGRES_PORT}}"
  
  MAIN_AUDIENCE: "{{MAIN_AUDIENCE}}"
  WELL_KNOWN_URL: "{{WELL_KNOWN_URL}}"
