apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  # Managements Endpoints
  AGREEMENT_MANAGEMENT_URL: "http://{{AGREEMENT_MANAGEMENT_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{AGREEMENT_MANAGEMENT_APPLICATION_PATH}}/{{AGREEMENT_MANAGEMENT_INTERFACE_VERSION}}"
  ATTRIBUTE_REGISTRY_MANAGEMENT_URL: "http://{{ATTRIBUTE_REGISTRY_MANAGEMENT_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_APPLICATION_PATH}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_INTERFACE_VERSION}}"
  AUTHORIZATION_MANAGEMENT_URL: "http://{{AUTHORIZATION_MANAGEMENT_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{AUTHORIZATION_MANAGEMENT_APPLICATION_PATH}}/{{AUTHORIZATION_MANAGEMENT_INTERFACE_VERSION}}"
  CATALOG_MANAGEMENT_URL: "http://{{CATALOG_MANAGEMENT_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{CATALOG_MANAGEMENT_APPLICATION_PATH}}/{{CATALOG_MANAGEMENT_INTERFACE_VERSION}}"
  PURPOSE_MANAGEMENT_URL: "http://{{PURPOSE_MANAGEMENT_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{PURPOSE_MANAGEMENT_APPLICATION_PATH}}/{{PURPOSE_MANAGEMENT_INTERFACE_VERSION}}"
  NOTIFIER_URL: "http://{{NOTIFIER_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{NOTIFIER_APPLICATION_PATH}}/{{NOTIFIER_INTERFACE_VERSION}}"
  

  POSTGRES_HOST: "{{POSTGRES_HOST}}"
  POSTGRES_PORT: "{{POSTGRES_PORT}}"
  
  WELL_KNOWN_URLS: "{{WELL_KNOWN_URLS}}"

  ENABLED_PROJECTIONS: "{{ENABLED_PROJECTIONS}}"