apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
        actorSystemName: {{SERVICE_NAME}}
      annotations:
        digest: {{IMAGE_DIGEST}} # Used to force deployment on same image version but different content
    spec:
      serviceAccountName: {{SERVICE_NAME}}
      containers:
        - name: {{SERVICE_NAME}}
          image: {{REPOSITORY}}/{{SERVICE_NAME}}:{{IMAGE_VERSION}}
          command: ["bin/{{SERVICE_NAME}}"]
          args: ["-Dconfig.override_with_env_vars=true"]
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 20
            failureThreshold: 15
            initialDelaySeconds: 60
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: {{BACKEND_SERVICE_PORT}}
              protocol: TCP
            - name: monitoring
              containerPort: 9095
              protocol: TCP
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REQUIRED_CONTACT_POINT_NR
              value: "{{REPLICAS}}"
            - name: WELL_KNOWN_URLS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: WELL_KNOWN_URLS
            - name: DEV_ENDPOINTS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: DEV_ENDPOINTS_ENABLED
          resources:
            requests:
              cpu: "{{SERVICE_RESOURCE_CPU}}"
              memory: "{{SERVICE_RESOURCE_MEM}}"
            limits:
              cpu: "{{SERVICE_RESOURCE_CPU}}"
              memory: "{{SERVICE_RESOURCE_MEM}}"
