kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: akka-discovery-role
  namespace: {{NAMESPACE}}
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: akka-discovery-binding
  namespace: {{NAMESPACE}}
subjects:
  # Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
  # For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
  - kind: ServiceAccount
    name: system:serviceaccount:{{NAMESPACE}}:{{SERVICE_NAME}}
roleRef:
  kind: Role
  name: akka-discovery
  apiGroup: rbac.authorization.k8s.io
