apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: "true"
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
    - port: {{BACKEND_SERVICE_PORT}}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9095
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    app: {{SERVICE_NAME}}
