apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-agreement-outbound-writer"
  KAFKA_GROUP_ID: "{{NAMESPACE}}-agreement-outbound-writer"
