apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_GROUP_ID
            - name: AGREEMENT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: common-kafka
                  key: AGREEMENT_TOPIC
            - name: PRODUCER_KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: KAFKA_CLIENT_ID
            - name: PRODUCER_KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: common-kafka
                  key: KAFKA_BROKERS
            - name: AGREEMENT_OUTBOUND_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: common-kafka
                  key: AGREEMENT_OUTBOUND_TOPIC
            - name: TOPIC_STARTING_OFFSET
              value: "earliest"
