apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  POSTGRES_DB: "persistence_management"
  POSTGRES_SCHEMA: "{{NAMESPACE}}_notifications"
  NOTIFICATION_DYNAMO_TABLE_NAME: "{{NOTIFICATION_DYNAMO_TABLE_NAME}}"
  NOTIFICATION_QUEUE_READER_THREAD_POOL_SIZE: "{{NOTIFICATION_QUEUE_READER_THREAD_POOL_SIZE}}"