apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  POSTGRES_DB: "persistence_management"
  POSTGRES_SCHEMA: "{{NAMESPACE}}_organizations"
  DYNAMO_TABLE_NAME: "{{DYNAMO_TABLE_NAME}}"
  QUEUE_READER_THREAD_POOL_SIZE: "{{QUEUE_READER_THREAD_POOL_SIZE}}"