apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PEC_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PEC_QUEUE_URL
            - name: PEC_SMTP_SENDER
              valueFrom:
                secretKeyRef:
                  name: smtp-certified
                  key: PEC_SMTP_SENDER
            - name: PEC_SMTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PEC_SMTP_ADDRESS
            - name: PEC_SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PEC_SMTP_PORT
            - name: PEC_WITH_SSL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PEC_WITH_SSL
            - name: PEC_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-certified
                  key: PEC_SMTP_USER
            - name: PEC_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-certified
                  key: PEC_SMTP_PASSWORD
