#!/bin/bash

INTEROP_JWT_DURATION=3600

INTERNAL_TOKEN_JWT_ISSUER="interop.pagopa.it"
INTERNAL_TOKEN_JWT_SUBJECT="interop-m2m"
INTERNAL_TOKEN_JWT_AUDIENCE="interop.pagopa.it/m2m"
INTERNAL_TOKEN_JWT_DURATION_SECONDS=3600
