#!/bin/bash

INTEROP_JWT_DURATION_SECONDS=600
INTEROP_JWT_ISSUER="test.interop.pagopa.it"

CLIENT_ASSERTION_JWT_AUDIENCE="test.interop.pagopa.it/client-assertion"

AUTHORIZATION_SERVER_CPU_REQUEST="1"
AUTHORIZATION_SERVER_MEMORY_REQUEST="2Gi"
AUTHORIZATION_SERVER_CPU_LIMIT="4"
AUTHORIZATION_SERVER_MEMORY_LIMIT="8Gi"
