#!/bin/bash

INTEROP_JWT_DURATION_SECONDS=600
INTEROP_JWT_ISSUER="test.interop.pagopa.it"

CLIENT_ASSERTION_JWT_AUDIENCE="interop.uat.selfcare.pagopa.it/client-assertion"

AUTHORIZATION_SERVER_RESOURCE_CPU="500m"
AUTHORIZATION_SERVER_RESOURCE_MEM="2Gi"
