#!/bin/bash

INTEROP_SESSION_TOKEN_DURATION_SECONDS=600
INTEROP_SESSION_TOKEN_ISSUER="test.interop.pagopa.it"

INTERNAL_JWT_ISSUER="test.interop.pagopa.it"
INTERNAL_JWT_SUBJECT="test.interop-m2m"
INTERNAL_JWT_DURATION_SECONDS=3600