#!/bin/bash
NOTIFICATION_DYNAMO_TABLE_NAME="interop-notification-events"
NOTIFICATION_DYNAMO_INVERTED_INDEX_NAME="resourceId-index"
NOTIFICATION_QUEUE_READER_THREAD_POOL_SIZE=3

NOTIFIER_RESOURCE_CPU="500m"
NOTIFIER_RESOURCE_MEM="2Gi"
