#!/bin/bash

SELFCARE_BROKER_URLS="???" # TBD
SELFCARE_CONTRACTS_TOPIC_CLIENT_ID="interop-uat"
SELFCARE_CONTRACTS_TOPIC_GROUP_ID="interop-onboarding-uat"
SELFCARE_CONTRACTS_TOPIC_NAME="sc-contracts"

SELFCARE_ONBOARDING_CONSUMER_RESOURCE_CPU="250m"
SELFCARE_ONBOARDING_CONSUMER_RESOURCE_MEM="512Mi"