#!/bin/bash

# SPID
IDP_SERVICE_URL=$NAMESPACE-idp.$EXTERNAL_INGRESS_HOST
ADMIN_IDP_SERVICE_URL=$NAMESPACE-idp-admin.$INTERNAL_INGRESS_HOST
SPID_LOGIN_SERVICE_NAME="hub-spid-login-ms"
REDIS_SERVICE_NAME="redis"
