#!/bin/bash

# Services Versions

AGREEMENT_MANAGEMENT_IMAGE_VERSION="1.0.7"
AGREEMENT_PROCESS_IMAGE_VERSION="1.0.8"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="1.0.8"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="1.0.9"
AUTHORIZATION_PROCESS_IMAGE_VERSION="1.0.6"
AUTHORIZATION_SERVER_IMAGE_VERSION="1.0.6"
CATALOG_MANAGEMENT_IMAGE_VERSION="1.0.10"
CATALOG_PROCESS_IMAGE_VERSION="1.0.7"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="1.0.5"
PURPOSE_MANAGEMENT_IMAGE_VERSION="1.0.6"
PURPOSE_PROCESS_IMAGE_VERSION="1.0.8"
TENANT_MANAGEMENT_IMAGE_VERSION="1.0.4"
TENANT_PROCESS_IMAGE_VERSION="1.0.4"
API_GATEWAY_IMAGE_VERSION="1.0.12"
BACKEND_FOR_FRONTEND_IMAGE_VERSION="1.0.7"
NOTIFIER_IMAGE_VERSION="1.0.7"

FRONTEND_IMAGE_VERSION="1.0.17"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="1.0.12"
JOB_DETAILS_PERSISTER_IMAGE_VERSION="1.0.12"
JOB_TENANTS_CERTIFIED_ATTRIBUTES_UPDATER_IMAGE_VERSION="1.0.12"
JOB_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.12"
JOB_PADIGITALE_REPORT_GENERATOR_IMAGE_VERSION="1.0.12"
JOB_DASHBOARD_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.12"
