#!/bin/bash

# Services Versions

AGREEMENT_MANAGEMENT_IMAGE_VERSION="1.0.10"
AGREEMENT_PROCESS_IMAGE_VERSION="1.0.10"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="1.0.11"
ATTRIBUTE_REGISTRY_PROCESS_IMAGE_VERSION="1.0.1"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="1.0.11"
AUTHORIZATION_PROCESS_IMAGE_VERSION="1.0.10"
AUTHORIZATION_SERVER_IMAGE_VERSION="1.0.8"
CATALOG_MANAGEMENT_IMAGE_VERSION="1.0.12"
CATALOG_PROCESS_IMAGE_VERSION="1.0.9"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="1.0.10"
PURPOSE_MANAGEMENT_IMAGE_VERSION="1.0.8"
PURPOSE_PROCESS_IMAGE_VERSION="1.0.10"
TENANT_MANAGEMENT_IMAGE_VERSION="1.0.6"
TENANT_PROCESS_IMAGE_VERSION="1.0.7"
API_GATEWAY_IMAGE_VERSION="1.0.14"
BACKEND_FOR_FRONTEND_IMAGE_VERSION="1.0.11"
NOTIFIER_IMAGE_VERSION="1.0.9"

FRONTEND_IMAGE_VERSION="1.0.24"


JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="1.0.14"
JOB_DETAILS_PERSISTER_IMAGE_VERSION="1.0.14"
JOB_TENANTS_CERTIFIED_ATTRIBUTES_UPDATER_IMAGE_VERSION="1.0.14"
JOB_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.14"
JOB_PADIGITALE_REPORT_GENERATOR_IMAGE_VERSION="1.0.14"
JOB_DASHBOARD_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.14"
JOB_PRIVACY_NOTICES_UPDATER_IMAGE_VERSION="1.0.14"
JOB_ESERVICES_MONITORING_EXPORTER_IMAGE_VERSION="1.0.14"

JOB_DTD_CATALOG_EXPORTER_IMAGE_VERSION="1.0.0"
