apiVersion: v1
kind: ConfigMap
metadata:
  name: common-services-urls
  namespace: {{NAMESPACE}}
data:
  AUTHORIZATION_MANAGEMENT_URL: "interop-be-authorization-management.dev-refactor.svc.cluster.local:8088"
