apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        absolute_redirect off;

        location /ui {
            root   /usr/share/nginx/html;
            sub_filter_once off;
            sub_filter_types *;
            sub_filter **CSP_NONCE** $request_id;
            add_header Content-Security-Policy-Report-Only "default-src 'self'; object-src 'none'; connect-src 'self' https://api-eu.mixpanel.com/track/ {{PUBLIC_BUCKET_URL}}; script-src 'self' 'nonce-$request_id'; style-src 'self' 'unsafe-inline'; worker-src 'none'; font-src 'self'; img-src 'self' data:";
            add_header Strict-Transport-Security "max-age=31536000";
            add_header X-Content-Type-Options "nosniff";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header Referrer-Policy "no-referrer";
            rewrite /ui/index.html /ui permanent;
            try_files $uri /ui/index.html =404;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  env.js: |-
    window.pagopa_env = {
      AGREEMENT_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{AGREEMENT_PROCESS_APPLICATION_PATH}}/{{AGREEMENT_PROCESS_INTERFACE_VERSION}}",
      AUTHORIZATION_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{AUTHORIZATION_PROCESS_APPLICATION_PATH}}/{{AUTHORIZATION_PROCESS_INTERFACE_VERSION}}",
      AUTHORIZATION_SERVER_TOKEN_CREATION_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{AUTHORIZATION_SERVER_APPLICATION_PATH}}/token.oauth2",
      CATALOG_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{CATALOG_PROCESS_APPLICATION_PATH}}/{{CATALOG_PROCESS_INTERFACE_VERSION}}",
      PURPOSE_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{PURPOSE_PROCESS_APPLICATION_PATH}}/{{PURPOSE_PROCESS_INTERFACE_VERSION}}",
      SELFCARE_LOGIN_URL: "{{SELFCARE_LOGIN_URL}}",
      INTEROP_RESOURCES_BASE_URL: "{{PUBLIC_BUCKET_URL}}",
      BACKEND_FOR_FRONTEND_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{BACKEND_FOR_FRONTEND_APPLICATION_PATH}}/{{BACKEND_FOR_FRONTEND_INTERFACE_VERSION}}",
      API_GATEWAY_INTEFACE_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{API_GATEWAY_APPLICATION_PATH}}/{{API_GATEWAY_INTERFACE_VERSION}}/interface-specification.yml",
      MIXPANEL_PROJECT_ID: "{{MIXPANEL_PROJECT_ID}}",
      ONETRUST_DOMAIN_SCRIPT_ID: "{{ONETRUST_DOMAIN_SCRIPT_ID}}",
      CLIENT_ASSERTION_JWT_AUDIENCE: "{{CLIENT_ASSERTION_JWT_AUDIENCE}}",
      M2M_JWT_AUDIENCE: "{{M2M_JWT_AUDIENCE}}",
      STAGE: "{{STAGE}}"
    }
