apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        absolute_redirect off;

        location /ui {
            root   /usr/share/nginx/html;
            try_files $uri /ui/index.html =404;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  env.js: |-
    window.pagopa_env = {
      AGREEMENT_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{AGREEMENT_PROCESS_APPLICATION_PATH}}/{{AGREEMENT_PROCESS_INTERFACE_VERSION}}",
      ATTRIBUTE_REGISTRY_MANAGEMENT_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_APPLICATION_PATH}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_INTERFACE_VERSION}}",
      AUTHORIZATION_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{AUTHORIZATION_PROCESS_APPLICATION_PATH}}/{{AUTHORIZATION_PROCESS_INTERFACE_VERSION}}",
      AUTHORIZATION_SERVER_TOKEN_CREATION_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{AUTHORIZATION_SERVER_APPLICATION_PATH}}/token.oauth2",
      CATALOG_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{CATALOG_PROCESS_APPLICATION_PATH}}/{{CATALOG_PROCESS_INTERFACE_VERSION}}",
      PURPOSE_PROCESS_URL: "https://{{EXTERNAL_APPLICATION_HOST}}/{{PURPOSE_PROCESS_APPLICATION_PATH}}/{{PURPOSE_PROCESS_INTERFACE_VERSION}}",
      SELFCARE_LOGIN_URL: "{{SELFCARE_LOGIN_URL}}",
      INTEROP_RESOURCES_BASE_URL: "{{PUBLIC_BUCKET_URL}}",
      BACKEND_FOR_FRONTEND: "https://{{EXTERNAL_APPLICATION_HOST}}/{{BACKEND_FOR_FRONTEND_SERVICE_PATH}}/{{BACKEND_FOR_FRONTEND_INTERFACE_VERSION}}",
      MIXPANEL_PROJECT_ID: "{{MIXPANEL_PROJECT_ID}}"
    }