apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{SERVICE_NAME}}
          image: {{REPOSITORY}}/services/{{SERVICE_NAME}}:{{FRONTEND_IMAGE_VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP