apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: wodby/redis:3.2-2.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: REDIS_TIMEOUT
            - name: REDIS_TCP_KEEPALIVE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: REDIS_TCP_KEEPALIVE
            - name: REDIS_MAXMEMORY
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: REDIS_MAXMEMORY