#!/bin/bash

AGREEMENT_PROCESS_STORAGE_TYPE="S3"
AGREEMENT_PROCESS_STORAGE_CONTAINER="interop-application-documents-prod"
AGREEMENT_PROCESS_STORAGE_ENDPOINT=""

AGREEMENT_PROCESS_RESOURCE_CPU="2"
AGREEMENT_PROCESS_RESOURCE_MEM="2Gi"
