#!/bin/bash

ATTRIBUTES_LOADER_TOKEN_JWT_ISSUER="interop.selfcare.pagopa.it"
ATTRIBUTES_LOADER_TOKEN_JWT_SUBJECT="interop-attributes-loader"
ATTRIBUTES_LOADER_TOKEN_JWT_DURATION_SECONDS=3600

JOB_ATTRIBUTES_LOADER_RESOURCE_CPU="500"
JOB_ATTRIBUTES_LOADER_RESOURCE_MEM="1Gi"
