#!/bin/bash

INTEROP_JWT_DURATION_SECONDS=600
INTEROP_JWT_ISSUER="interop.selfcare.pagopa.it"

CLIENT_ASSERTION_JWT_AUDIENCE="interop.selfcare.pagopa.it/client-assertion"

AUTHORIZATION_SERVER_CPU_REQUEST="4"
AUTHORIZATION_SERVER_MEMORY_REQUEST="8Gi"
AUTHORIZATION_SERVER_CPU_LIMIT="4"
AUTHORIZATION_SERVER_MEMORY_LIMIT="8Gi"
