#!/bin/bash

INTEROP_JWT_DURATION_SECONDS=600
INTEROP_JWT_ISSUER="interop.pagopa.it"

CLIENT_ASSERTION_JWT_AUDIENCE="auth.interop.pagopa.it/client-assertion"

AUTHORIZATION_SERVER_RESOURCE_CPU="4"
AUTHORIZATION_SERVER_RESOURCE_MEM="8Gi"

AUTH_SERVER_RATE_LIMITER_MAX_REQUESTS="30"
AUTH_SERVER_RATE_LIMITER_BURST_PERCENTAGE="1.2"
AUTH_SERVER_RATE_LIMITER_RATE_INTERVAL="1.second"
AUTH_SERVER_RATE_LIMITER_TIMEOUT="200.milliseconds"
