#!/bin/bash

INTEROP_JWT_DURATION_SECONDS=600
INTEROP_JWT_ISSUER="prod.interop.pagopa.it"

CLIENT_ASSERTION_JWT_AUDIENCE="prod.interop.pagopa.it/client-assertion"

AUTHORIZATION_SERVER_RESOURCE_CPU="4"
AUTHORIZATION_SERVER_RESOURCE_MEM="8Gi"
