#!/bin/bash

CATALOG_PROCESS_STORAGE_TYPE="S3"
CATALOG_PROCESS_STORAGE_CONTAINER="interop-application-documents-prod"
CATALOG_PROCESS_STORAGE_ENDPOINT=""

CATALOG_PROCESS_RESOURCE_CPU="2"
CATALOG_PROCESS_RESOURCE_MEM="2Gi"
