#!/bin/bash

CATALOG_MANAGEMENT_STORAGE_TYPE="S3"
CATALOG_MANAGEMENT_STORAGE_CONTAINER="interop-application-documents-prod"
CATALOG_MANAGEMENT_STORAGE_ENDPOINT=""

CATALOG_MANAGEMENT_RESOURCE_CPU="2"
CATALOG_MANAGEMENT_RESOURCE_MEM="2Gi"
