#!/bin/bash

ESERVICE_MONITORING_EXPORT_BUCKET="interop-probing-eservices-prod"
ESERVICE_MONITORING_EXPORT_FILENAME="eservices"
TENANTS_COLLECTION_NAME="tenants"
ESERVICES_COLLECTION_NAME="eservices"

JOB_ESERVICES_MONITORING_EXPORTER_RESOURCE_CPU="500m"
JOB_ESERVICES_MONITORING_EXPORTER_RESOURCE_MEM="1Gi"

PRODUCERS_ALLOW_LIST="$PAGOPA_TENANT_ID"
