#!/bin/bash

TENANTS_COLLECTION_NAME="tenants"
PURPOSES_COLLECTION_NAME="purposes"
AGREEMENTS_COLLECTION_NAME="agreements"
ESERVICES_COLLECTION_NAME="eservices"

ATHENA_TOKENS_DB_NAME="generated_jwt_prod"
ATHENA_OUTPUT_BUCKET="interop-athena-query-results-prod"

SMTP_SECURE=true

JOB_METRICS_REPORT_GENERATOR_RESOURCE_CPU="4"
JOB_METRICS_REPORT_GENERATOR_RESOURCE_MEM="8Gi"
