#!/bin/bash

INTERFACES_CONTAINER="interop-application-documents-prod"

REPORTS_CONTAINER="interop-platform-metrics-prod"
PA_DIGITALE_STORAGE_PATH="pa-digitale"
AGREEMENTS_CSV_STORAGE_PATH="agreements/csv"
AGREEMENTS_JSON_STORAGE_PATH="agreements/json"

ESERVICES_COLLECTION_NAME="eservices"
TENANTS_COLLECTION_NAME="tenants"

JOB_PADIGITALE_REPORT_GENERATOR_RESOURCE_CPU="500m"
JOB_PADIGITALE_REPORT_GENERATOR_RESOURCE_MEM="1Gi"
