#!/bin/bash

PRIVACY_NOTICES_UPDATER_DYNAMO_TABLE_NAME="interop-privacy-notices-prod"
ONE_TRUST_TOKEN_CREATION_URL="https://app-de.onetrust.com/api/access/v1/oauth/token"
ONE_TRUST_PRIVACY_NOTICES_LIST_URL="https://app-de.onetrust.com/api/privacynotice/v2/privacynotices"
PRIVACY_NOTICES_UPDATER_PRIVACY_POLICY_UUID="0df21ff6-3e8f-4320-af8f-23dea9135d57"
PRIVACY_NOTICES_UPDATER_TERMS_OF_SERVICE_UUID="6bf8412a-41a7-41a0-82dc-26286ce61b1a"

JOB_PRIVACY_NOTICES_UPDATER_RESOURCE_CPU="500m"
JOB_PRIVACY_NOTICES_UPDATER_RESOURCE_MEM="1Gi"
