#!/bin/bash

SELFCARE_BROKER_URLS="???" # TBD
KAFKA_CLIENT_ID="interop-prod"
KAFKA_GROUP_ID="interop-onboarding-prod"
TOPIC_NAME="sc-contracts"

SELFCARE_ONBOARDING_CONSUMER_RESOURCE_CPU="250m"
SELFCARE_ONBOARDING_CONSUMER_RESOURCE_MEM="512Mi"