#!/bin/bash

SELFCARE_BROKER_URLS="selc-p-eventhub-ns.servicebus.windows.net:9093"
SELFCARE_CONTRACTS_TOPIC_CLIENT_ID="interop-prod"
SELFCARE_CONTRACTS_TOPIC_GROUP_ID="interop-onboarding-prod"
SELFCARE_CONTRACTS_TOPIC_NAME="sc-contracts"

SELFCARE_ONBOARDING_CONSUMER_RESOURCE_CPU="250m"
SELFCARE_ONBOARDING_CONSUMER_RESOURCE_MEM="512Mi"