#!/bin/bash

# Services Versions
AGREEMENT_MANAGEMENT_IMAGE_VERSION="1.0.5"
AGREEMENT_PROCESS_IMAGE_VERSION="1.0.7"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="1.0.7"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="1.0.8"
AUTHORIZATION_PROCESS_IMAGE_VERSION="1.0.5"
AUTHORIZATION_SERVER_IMAGE_VERSION="1.0.5"
CATALOG_MANAGEMENT_IMAGE_VERSION="1.0.9"
CATALOG_PROCESS_IMAGE_VERSION="1.0.6"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="1.0.4"
PURPOSE_MANAGEMENT_IMAGE_VERSION="1.0.5"
PURPOSE_PROCESS_IMAGE_VERSION="1.0.7"
TENANT_MANAGEMENT_IMAGE_VERSION="1.0.3"
TENANT_PROCESS_IMAGE_VERSION="1.0.2"
API_GATEWAY_IMAGE_VERSION="1.0.11"
BACKEND_FOR_FRONTEND_IMAGE_VERSION="1.0.5"
NOTIFIER_IMAGE_VERSION="1.0.6"

FRONTEND_IMAGE_VERSION="1.0.14"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="1.0.10"
JOB_DETAILS_PERSISTER_IMAGE_VERSION="1.0.10"
JOB_TENANTS_CERTIFIED_ATTRIBUTES_UPDATER_IMAGE_VERSION="1.0.10"
JOB_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.10"
JOB_PADIGITALE_REPORT_GENERATOR_IMAGE_VERSION="placeholder"
JOB_DASHBOARD_METRICS_REPORT_GENERATOR_IMAGE_VERSION="placeholder"
