#!/bin/bash

# Services Versions
AGREEMENT_MANAGEMENT_IMAGE_VERSION="1.0.4"
AGREEMENT_PROCESS_IMAGE_VERSION="1.0.6"
ATTRIBUTE_REGISTRY_MANAGEMENT_IMAGE_VERSION="1.0.6"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="1.0.7"
AUTHORIZATION_PROCESS_IMAGE_VERSION="1.0.4"
AUTHORIZATION_SERVER_IMAGE_VERSION="1.0.4"
CATALOG_MANAGEMENT_IMAGE_VERSION="1.0.7"
CATALOG_PROCESS_IMAGE_VERSION="1.0.4"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="1.0.3"
PURPOSE_MANAGEMENT_IMAGE_VERSION="1.0.4"
PURPOSE_PROCESS_IMAGE_VERSION="1.0.5"
TENANT_MANAGEMENT_IMAGE_VERSION="1.0.2"
TENANT_PROCESS_IMAGE_VERSION="1.0.1"
API_GATEWAY_IMAGE_VERSION="1.0.7"
BACKEND_FOR_FRONTEND_IMAGE_VERSION="1.0.3"
NOTIFIER_IMAGE_VERSION="1.0.5"

FRONTEND_IMAGE_VERSION="1.0.13"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="1.0.7"
JOB_DETAILS_PERSISTER_IMAGE_VERSION="1.0.7"
JOB_TENANTS_CERTIFIED_ATTRIBUTES_UPDATER_IMAGE_VERSION="1.0.7"
