#!/bin/bash

# Services Versions

AGREEMENT_READMODEL_WRITER_IMAGE_VERSION="2.0.9"
AGREEMENT_PROCESS_IMAGE_VERSION="2.0.9"
ATTRIBUTE_REGISTRY_PROCESS_IMAGE_VERSION="2.0.9"
ATTRIBUTE_REGISTRY_READMODEL_WRITER_IMAGE_VERSION="2.0.9"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="1.0.17"
AUTHORIZATION_PROCESS_IMAGE_VERSION="1.0.19"
AUTHORIZATION_SERVER_IMAGE_VERSION="1.0.14"
AUTHORIZATION_UPDATER_IMAGE_VERSION="2.0.9"
CATALOG_READMODEL_WRITER_IMAGE_VERSION="2.0.9"
CATALOG_PROCESS_IMAGE_VERSION="2.0.9"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="1.0.15"
PURPOSE_READMODEL_WRITER_IMAGE_VERSION="2.0.9"
PURPOSE_PROCESS_IMAGE_VERSION="2.0.9"
TENANT_MANAGEMENT_IMAGE_VERSION="1.0.11"
TENANT_PROCESS_IMAGE_VERSION="1.0.17"
API_GATEWAY_IMAGE_VERSION="1.0.24"
BACKEND_FOR_FRONTEND_IMAGE_VERSION="1.0.29"
NOTIFIER_IMAGE_VERSION="1.0.19"
NOTIFIER_SEEDER_IMAGE_VERSION="2.0.9"

FRONTEND_IMAGE_VERSION="1.0.69"

SELFCARE_ONBOARDING_CONSUMER_IMAGE_VERSION="1.0.42"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="1.0.31"
JOB_DETAILS_PERSISTER_IMAGE_VERSION="1.0.31"
JOB_TENANTS_CERTIFIED_ATTRIBUTES_UPDATER_IMAGE_VERSION="1.0.31"
JOB_PADIGITALE_REPORT_GENERATOR_IMAGE_VERSION="1.0.31"
JOB_DASHBOARD_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.31"
JOB_ESERVICES_MONITORING_EXPORTER_IMAGE_VERSION="1.0.31"
ESERVICE_DESCRIPTORS_ARCHIVER_IMAGE_VERSION="2.0.9"
AGREEMENT_EMAIL_SENDER_IMAGE_VERSION="2.0.9"

JOB_DTD_CATALOG_EXPORTER_IMAGE_VERSION="1.0.42"
JOB_ONE_TRUST_NOTICES_IMAGE_VERSION="1.0.42"
JOB_ANAC_CERTIFIED_ATTRIBUTES_IMPORTER_IMAGE_VERSION="1.0.42"
JOB_IVASS_CERTIFIED_ATTRIBUTES_IMPORTER_IMAGE_VERSION="1.0.42"
JOB_PN_CONSUMERS_IMAGE_VERSION="1.0.42"
JOB_DATALAKE_DATA_EXPORT_IMAGE_VERSION="1.0.42"
JOB_METRICS_REPORT_GENERATOR_IMAGE_VERSION="1.0.42"
