# TODO Temporary, just until we have test rds configured
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: "true"
  name: postgres
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres