apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  INTEROP_RSA_PRIVATE_VAULT_PATH: "secret/data/interop/keys/rsa/jwk/private"
  INTEROP_JWT_DURATION: "{{INTEROP_JWT_DURATION}}"
  INTEROP_JWT_ISSUER: "{{INTEROP_JWT_ISSUER}}"

  INTERNAL_JWT_ISSUER: "{{INTERNAL_JWT_ISSUER}}"
  INTERNAL_JWT_SUBJECT: "{{INTERNAL_JWT_SUBJECT}}"
  INTERNAL_JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
  INTERNAL_JWT_DURATION_SECONDS: "{{INTERNAL_JWT_DURATION_SECONDS}}"

  CLIENT_ASSERTION_JWT_AUDIENCE: "{{CLIENT_ASSERTION_JWT_AUDIENCE}}"
