apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ACCEPTED_AUDIENCES
            - name: CATALOG_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: CATALOG_MANAGEMENT_URL
            - name: TENANT_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: TENANT_MANAGEMENT_URL
            - name: AGREEMENT_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_MANAGEMENT_URL
            - name: AUTHORIZATION_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AUTHORIZATION_MANAGEMENT_URL
            - name: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
            - name: STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_TYPE
            - name: STORAGE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_CONTAINER
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: STORAGE_ENDPOINT
            - name: ARCHIVING_PURPOSES_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ARCHIVING_PURPOSES_QUEUE_NAME
            - name: ARCHIVING_ESERVICES_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ARCHIVING_ESERVICES_QUEUE_NAME
            - name: AGREEMENT_CONTRACTS_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_CONTRACTS_PATH
            - name: CONSUMER_DOCS_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: CONSUMER_DOCS_PATH
            - name: CERTIFIED_MAIL_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: CERTIFIED_MAIL_QUEUE_NAME
            - name: SELFCARE_V2_API_KEY
              valueFrom:
                secretKeyRef:
                  name: selfcare-v2
                  key: SELFCARE_V2_API_KEY
            - name: SELFCARE_V2_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: SELFCARE_V2_URL
            - name: MESSAGE_GROUP_ID
              valueFrom:
                  configMapKeyRef:
                    name: {{SERVICE_NAME}}
                    key: MESSAGE_GROUP_ID
