#!/bin/bash

AUTHORIZATION_PROCESS_SERVICE_NAME="interop-be-authorization-process-refactor"

AUTHORIZATION_PROCESS_RESOURCE_CPU="500m"
AUTHORIZATION_PROCESS_RESOURCE_MEM="2Gi"

MAX_KEYS_PER_CLIENT=100
MAX_KEYS_PER_PRODUCER_KEYCHAIN=30
