#!/bin/bash

# Services Versions

AGREEMENT_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
AGREEMENT_PROCESS_IMAGE_VERSION="2.0.17"
ATTRIBUTE_REGISTRY_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
ATTRIBUTE_REGISTRY_PROCESS_IMAGE_VERSION="2.0.17"
AUTHORIZATION_MANAGEMENT_IMAGE_VERSION="1.0.x-latest"
AUTHORIZATION_PROCESS_IMAGE_VERSION="2.0.17"
AUTHORIZATION_SERVER_IMAGE_VERSION="1.0.x-latest"
AUTHORIZATION_UPDATER_IMAGE_VERSION="2.0.17"
CATALOG_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
CATALOG_PROCESS_IMAGE_VERSION="2.0.17"
CLIENT_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
COMPUTE_AGREEMENTS_CONSUMER_IMAGE_VERSION="2.0.17"
KEY_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
PRODUCER_KEYCHAIN_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
PRODUCER_KEY_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
PARTY_REGISTRY_PROXY_IMAGE_VERSION="1.0.x-latest"
PURPOSE_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
PURPOSE_PROCESS_IMAGE_VERSION="2.0.17"
TENANT_READMODEL_WRITER_IMAGE_VERSION="2.0.17"
TENANT_PROCESS_IMAGE_VERSION="2.0.17"
API_GATEWAY_IMAGE_VERSION="2.0.17"
BACKEND_FOR_FRONTEND_IMAGE_VERSION="2.0.17"
NOTIFIER_IMAGE_VERSION="1.0.x-latest"
NOTIFIER_SEEDER_IMAGE_VERSION="2.0.17"
ESERVICE_DESCRIPTORS_ARCHIVER_IMAGE_VERSION="2.0.17"

FRONTEND_IMAGE_VERSION="dev-latest"

SELFCARE_ONBOARDING_CONSUMER_IMAGE_VERSION="2.0.17"

JOB_ATTRIBUTES_LOADER_IMAGE_VERSION="1.0.x-latest"
JOB_DETAILS_PERSISTER_IMAGE_VERSION="1.0.x-latest"
JOB_TENANTS_CERTIFIED_ATTRIBUTES_UPDATER_IMAGE_VERSION="1.0.x-latest"

JOB_PADIGITALE_REPORT_GENERATOR_IMAGE_VERSION="1.0.x-latest"
JOB_ESERVICES_MONITORING_EXPORTER_IMAGE_VERSION="1.0.x-latest"
AGREEMENT_EMAIL_SENDER_IMAGE_VERSION="2.0.17"

JOB_DTD_CATALOG_EXPORTER_IMAGE_VERSION="2.0.17"
JOB_ONE_TRUST_NOTICES_IMAGE_VERSION="2.0.17"
JOB_ANAC_CERTIFIED_ATTRIBUTES_IMPORTER_IMAGE_VERSION="2.0.17"
JOB_IVASS_CERTIFIED_ATTRIBUTES_IMPORTER_IMAGE_VERSION="2.0.17"
JOB_PN_CONSUMERS_IMAGE_VERSION="2.0.17"
JOB_DATALAKE_DATA_EXPORT_IMAGE_VERSION="2.0.17"