apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  POSTGRES_DB: "persistence_management"
  POSTGRES_SCHEMA: "{{NAMESPACE}}_agreement"
  CQRS_PROJECTION_COLLECTION_NAME: "agreements"
  ACCEPTED_AUDIENCES: "{{UI_JWT_AUDIENCE}},{{M2M_JWT_AUDIENCE}}"