apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-producer-key"
  KAFKA_GROUP_ID: "{{NAMESPACE}}-producer-key-readmodel-writer"
