#!/bin/bash

PRIVACY_NOTICES_LANGS=it
PRIVACY_NOTICES_CONTENT_STORAGE_BUCKET=interop-privacy-notices-content-att
PRIVACY_NOTICES_HISTORY_STORAGE_BUCKET=interop-privacy-notices-history-att

JOB_ONE_TRUST_NOTICES_RESOURCE_CPU="500m"
JOB_ONE_TRUST_NOTICES_RESOURCE_MEM="1Gi"
