apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ACCEPTED_AUDIENCES
            - name: AGREEMENT_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_MANAGEMENT_URL
            - name: TENANT_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: TENANT_MANAGEMENT_URL
            - name: AGREEMENT_PROCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_PROCESS_URL
