apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  KAFKA_CLIENT_ID: "{{NAMESPACE}}-pagopa-interop-client-purpose-updater"
  KAFKA_GROUP_ID: "{{NAMESPACE}}-client-purpose-updater"

  INTERNAL_JWT_KID: "{{RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{INTERNAL_JWT_SUBJECT}}"
  INTERNAL_JWT_ISSUER: "{{INTERNAL_JWT_ISSUER}}"
  INTERNAL_JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
  INTERNAL_JWT_SECONDS_DURATION: "{{CLIENT_PURPOSE_UPDATER_JWT_DURATION_SECONDS}}"

  AUTHORIZATION_PROCESS_URL: "http://{{AUTHORIZATION_PROCESS_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}"
