apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  STORAGE_TYPE: "{{AGREEMENT_PROCESS_STORAGE_TYPE}}"
  STORAGE_CONTAINER: "{{AGREEMENT_PROCESS_STORAGE_CONTAINER}}"
  STORAGE_ENDPOINT: "{{AGREEMENT_PROCESS_STORAGE_ENDPOINT}}"

  ACCEPTED_AUDIENCES: "{{UI_JWT_AUDIENCE}},{{M2M_JWT_AUDIENCE}},{{INTERNAL_JWT_AUDIENCE}}"
  USER_REGISTRY_URL: "{{USER_REGISTRY_URL}}"
  PARTY_PROCESS_URL: "{{PARTY_PROCESS_URL}}"
   
  AGREEMENT_CONTRACTS_PATH: "{{NAMESPACE}}/agreement/contracts"
  CONSUMER_DOCS_PATH: "{{NAMESPACE}}/agreement/consumer-docs"

  CERTIFIED_MAIL_QUEUE_NAME: "{{CERTIFIED_MAIL_QUEUE_NAME}}"

  MESSAGE_GROUP_ID: "pec_message_group_id"