apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: CATALOG_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: CATALOG_MANAGEMENT_URL
            - name: AGREEMENT_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_MANAGEMENT_URL
            - name: PARTY_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_MANAGEMENT_URL
            - name: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
