apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  TENANTS_COLLECTION_NAME: "{{TENANTS_COLLECTION_NAME}}"
  PURPOSES_COLLECTION_NAME: "{{PURPOSES_COLLECTION_NAME}}"
  SMTP_ADDRESS: "{{SMTP_ADDRESS}}"
  SMTP_PORT: "{{SMTP_PORT}}"
  SMTP_SECURE: "true"
  PN_ESERVICE_ID: "{{PN_ESERVICE_ID}}"
  COMUNI_E_LORO_CONSORZI_E_ASSOCIAZIONI_ATTRIBUTE_ID: "{{COMUNI_E_LORO_CONSORZI_E_ASSOCIAZIONI_ATTRIBUTE_ID}}"
  REPORT_SENDER: "{{SMTP_SECURE}}"