#!/bin/bash

CATALOG_PROCESS_STORAGE_TYPE="S3"
CATALOG_PROCESS_STORAGE_CONTAINER="interop-application-documents-qa"
CATALOG_PROCESS_STORAGE_ENDPOINT=""

CATALOG_PROCESS_RESOURCE_CPU="500m"
CATALOG_PROCESS_RESOURCE_MEM="2Gi"
