apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: {{REPOSITORY}}/services/{{SERVICE_NAME}}:{{CATALOG_PROCESS_IMAGE_VERSION}}
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_ACCESS_KEY_ID
            - name: CATALOG_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: CATALOG_MANAGEMENT_URL
            - name: AGREEMENT_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: AGREEMENT_MANAGEMENT_URL
            - name: PARTY_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_MANAGEMENT_URL
            - name: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
            - name: STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_MANAGEMENT_STORAGE_TYPE
            - name: STORAGE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_MANAGEMENT_STORAGE_CONTAINER
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_MANAGEMENT_STORAGE_ENDPOINT
            - name: STORAGE_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: STORAGE_USR
            - name: STORAGE_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: storage
                  key: STORAGE_PSW
            - name: WELL_KNOWN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: WELL_KNOWN_URL
