apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  ORG_ISSUER: "https://spid.agid.gov.it/cd"
  ORG_URL: "https://pagopa.gov.it"
  # ACS_BASE_URL: "http://localhost:9090"
  ACS_BASE_URL: "https://{{INGRESS_HOST}}/{{NAMESPACE}}/{{IDP_SERVICE_URL}}"
  ORG_DISPLAY_NAME: "Organization display name"
  ORG_NAME: "Organization name"

  AUTH_N_CONTEXT: "https://www.spid.gov.it/SpidL2"

  SPID_ATTRIBUTES: "address,email,name,familyName,fiscalNumber,mobilePhone"

  ENDPOINT_ACS: "/acs"
  ENDPOINT_ERROR: "/error"
  ENDPOINT_SUCCESS: "/success"
  ENDPOINT_LOGIN: "/login"
  ENDPOINT_METADATA: "/metadata"
  ENDPOINT_LOGOUT: "/logout"

  # SPID_VALIDATOR_URL: "http://localhost"
  SPID_VALIDATOR_URL: "https://{{INGRESS_HOST}}/{{NAMESPACE}}/{{IDP_SERVICE_URL}}"
  # SPID_TESTENV_URL: "http://{{IDP_SERVICE_URL}}:8088" # IdP
  # SPID_TESTENV_URL: "https://{{EXTERNAL_INGRESS_HOST}}/{{NAMESPACE}}/{{IDP_SERVICE_URL}}" # IdP
  SPID_TESTENV_URL: "https://{{INGRESS_HOST}}/{{NAMESPACE}}/{{IDP_SERVICE_URL}}" # IdP

  REDIS_URL: "{{REDIS_URL}}"
  REDIS_TLS_ENABLED: "false"

  ENABLE_JWT: "true"
  INCLUDE_SPID_USER_ON_INTROSPECTION: "true"

  TOKEN_EXPIRATION: "3600"
  JWT_TOKEN_ISSUER: "SPID"

  ENABLE_USER_REGISTRY: "false"
  USER_REGISTRY_URL: "https://{{USER_REGISTRY_MANAGEMENT_SERVICE_NAME}}"

  ENABLE_ADE_AA: "false"
  ADE_AA_API_ENDPOINT: "http://ade-aa-ms-mock:3000" # ADE Mock to authorize user and enrich jwt
  ENDPOINT_L1_SUCCESS: "/success/l1"
  L1_TOKEN_EXPIRATION: "60"
  L1_TOKEN_HEADER_NAME: "x-token"
  L2_TOKEN_EXPIRATION: "3600"
  APPINSIGHTS_INSTRUMENTATIONKEY: "foo" #?
  REQUIRED_ATTRIBUTES_SERVICE_NAME: "Service Name"

  ENABLE_FULL_OPERATOR_METADATA: "true"
  COMPANY_EMAIL: "company@email.com"
  COMPANY_FISCAL_CODE: "12312312311"
  COMPANY_IPA_CODE: "IPA_CODE"
  COMPANY_NAME: "Company S.r.l"
  COMPANY_VAT_NUMBER: "12312312311"

  SERVER_PORT: "9090"