apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: ghcr.io/pagopa/hub-spid-login-ms:{{SPID_LOGIN_MODULE_IMAGE_VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: spid-login
              containerPort: 9090
              protocol: TCP
          envFrom:
            - configMapRef:
              name: {{SERVICE_NAME}}
          env:
            - name: METADATA_PUBLIC_CERT
              valueFrom:
                secretKeyRef:
                  name: spid-login
                  key: METADATA_PUBLIC_CERT
            - name: METADATA_PRIVATE_CERT
              valueFrom:
                secretKeyRef:
                  name: spid-login
                  key: METADATA_PRIVATE_CERT
            - name: JWT_TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: spid-login
                  key: JWT_TOKEN_PRIVATE_KEY