# TODO This must be moved to external ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{INTERNAL_INGRESS_CLASS}}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    external-dns.alpha.kubernetes.io/hostname: {{INTERNAL_APPLICATION_HOST}}
    kubernetes.io/tls-acme: "true"
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  tls:
    - hosts:
        - {{INTERNAL_APPLICATION_HOST}}
  rules:
    - host: "{{INTERNAL_APPLICATION_HOST}}"
      http:
        paths:
          - path: "/{{SERVICE_NAME}}/(.*)"
            pathType: Prefix
            backend:
              service:
                name: {{SERVICE_NAME}}
                port: 
                  number: 9090