apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  EC_KEYS_IDENTIFIERS: "{{EC_KEYS_IDENTIFIERS}}"
  RSA_KEYS_IDENTIFIERS: "{{RSA_KEYS_IDENTIFIERS}}"
  VAULT_SIGNATURE_ROUTE: "{{VAULT_SIGNATURE_ROUTE}}"
  ATTRIBUTE_REGISTRY_MANAGEMENT_URL: "http://{{ATTRIBUTE_REGISTRY_MANAGEMENT_SERVICE_NAME}}:{{BACKEND_SERVICE_PORT}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_APPLICATION_PATH}}/{{ATTRIBUTE_REGISTRY_MANAGEMENT_INTERFACE_VERSION}}"
  JWT_ISSUER: "{{ATTRIBUTES_LOADER_TOKEN_JWT_ISSUER}}"
  JWT_SUBJECT: "{{ATTRIBUTES_LOADER_TOKEN_JWT_SUBJECT}}"
  JWT_AUDIENCE: "{{INTERNAL_JWT_AUDIENCE}}"
  JWT_DURATION_SECONDS: "{{ATTRIBUTES_LOADER_TOKEN_JWT_DURATION_SECONDS}}"