apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  schedule: "* 6 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
      annotations:
        digest: {{IMAGE_DIGEST}} # Used to force deployment on same image version but different content
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{SERVICE_NAME}}
              image: {{REPOSITORY}}/{{SERVICE_NAME}}:{{JOB_ATTRIBUTES_LOADER_IMAGE_VERSION}}
              imagePullPolicy: Always
              command: ["bin/{{SERVICE_NAME}}"]
              args: ["-Dconfig.override_with_env_vars=true"]
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: VAULT_ADDR
                  valueFrom:
                    secretKeyRef:
                      name: vault
                      key: VAULT_ADDR
                - name: VAULT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: vault
                      key: VAULT_TOKEN
                - name: JWT_ISSUER
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: JWT_ISSUER
                - name: JWT_SUBJECT
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: JWT_SUBJECT
                - name: JWT_AUDIENCE
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: JWT_AUDIENCE
                - name: JWT_DURATION_SECONDS
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: JWT_DURATION_SECONDS
                - name: EC_KEYS_IDENTIFIERS
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: EC_KEYS_IDENTIFIERS
                - name: RSA_KEYS_IDENTIFIERS
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: RSA_KEYS_IDENTIFIERS
                - name: VAULT_SIGNATURE_ROUTE
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: VAULT_SIGNATURE_ROUTE
                - name: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{SERVICE_NAME}}
                      key: ATTRIBUTE_REGISTRY_MANAGEMENT_URL
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "30m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"