#!/bin/bash

AGREEMENT_PROCESS_STORAGE_TYPE="S3"
AGREEMENT_PROCESS_STORAGE_CONTAINER="interop-application-documents-att-es1"
AGREEMENT_PROCESS_STORAGE_ENDPOINT=""
ARCHIVING_PURPOSES_QUEUE_NAME="archived-agreements-for-purposes"
ARCHIVING_ESERVICES_QUEUE_NAME="archived-agreements-for-eservices"

AGREEMENT_PROCESS_RESOURCE_CPU="500m"
AGREEMENT_PROCESS_RESOURCE_MEM="2Gi"
