#!/bin/bash

ATTRIBUTES_LOADER_TOKEN_JWT_ISSUER="att.interop.pagopa.it"
ATTRIBUTES_LOADER_TOKEN_JWT_SUBJECT="att.interop-attributes-loader"
ATTRIBUTES_LOADER_TOKEN_JWT_DURATION_SECONDS=43200

JOB_ATTRIBUTES_LOADER_RESOURCE_CPU="500m"
JOB_ATTRIBUTES_LOADER_RESOURCE_MEM="1Gi"
