#!/bin/bash

CATALOG_MANAGEMENT_STORAGE_TYPE="S3"
CATALOG_MANAGEMENT_STORAGE_CONTAINER="interop-application-documents-att-es1"
CATALOG_MANAGEMENT_STORAGE_ENDPOINT=""

CATALOG_MANAGEMENT_RESOURCE_CPU="500m"
CATALOG_MANAGEMENT_RESOURCE_MEM="2Gi"
