#!/bin/bash

AGREEMENT_PROCESS_SERVICE_NAME="interop-be-agreement-process"
AGREEMENT_PROCESS_STORAGE_TYPE="S3"
AGREEMENT_PROCESS_STORAGE_CONTAINER="interop-application-documents-refactor-dev"
AGREEMENT_PROCESS_STORAGE_ENDPOINT=""
ARCHIVING_PURPOSES_QUEUE_NAME="archived-agreements-for-purposes-refactor"
ARCHIVING_ESERVICES_QUEUE_NAME="archived-agreements-for-eservices-refactor"

AGREEMENT_PROCESS_RESOURCE_CPU="500m"
AGREEMENT_PROCESS_RESOURCE_MEM="2Gi"
