#!/bin/bash

CATALOG_PROCESS_SERVICE_NAME="interop-be-catalog-process-refactor"
CATALOG_PROCESS_STORAGE_TYPE="S3"
CATALOG_PROCESS_STORAGE_CONTAINER="interop-application-documents-refactor-dev"
CATALOG_PROCESS_STORAGE_ENDPOINT=""
CATALOG_PROCESS_ESERVICE_DOCUMENTS_PATH="eservices/docs"

CATALOG_PROCESS_RESOURCE_CPU="500m"
CATALOG_PROCESS_RESOURCE_MEM="2Gi"
