#!/bin/bash

DASHBOARD_DATA_BUCKET="interop-public-dashboards-dev"
DASHBOARD_DATA_FILENAME="kpis-dashboard.json"
TOKENS_BUCKET="interop-generated-jwt-details-refactor-dev"
TOKENS_BASE_PATH="/"
TENANTS_COLLECTION_NAME="tenants"
AGREEMENTS_COLLECTION_NAME="agreements"
PURPOSES_COLLECTION_NAME="purposes"
ESERVICES_COLLECTION_NAME="eservices"

JOB_DASHBOARD_METRICS_REPORT_GENERATOR_RESOURCE_CPU="4000m"
JOB_DASHBOARD_METRICS_REPORT_GENERATOR_RESOURCE_MEM="8Gi"
