name: Deploy Service

on:
  workflow_call:
    inputs:
      runner_name:
        description: 'Name (label) of the self-hosted runner'
        type: string
        required: true
      environment:
        description: 'Environment name'
        type: string
        required: true
      kustomize_overlay_path:
        description: 'Path to folder with kustomize overlay for this service'
        type: string
        required: true
      service_name_var_name:
        description: 'Name of the environment variable containing the service name'
        type: string
        required: true
      image_version_var_name:
        description: 'Name of the environment variable containing the image version for this service'
        type: string
        required: true
      resource_cpu_var_name:
        description: 'Name of the environment variable containing the CPU to allocate for this service'
        type: string
        required: true
      resource_mem_var_name:
        description: 'Name of the environment variable containing the memory to allocate for this service'
        type: string
        required: true

jobs:
  deploy_service:
    name: Deploy Service
    runs-on: [self-hosted, "${{ inputs.runner_name }}"]
    environment: ${{ inputs.environment }}
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ENVIRONMENT: ${{ inputs.environment }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update Kubeconfig
        id: update_kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      #   with:
      #     registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Apply Kustomize
        id: apply_kustomize
        run: |
          source $CONFIG_FILE
          source ./deployment_functions.sh

          serviceName="${${{inputs.service_name_var_name}}}"
          imageVersion="${${{inputs.image_version_var_name}}}"
          resourceCpu="${${{inputs.resource_cpu_var_name}}}"
          resourceMem="${${{inputs.resource_mem_var_name}}}"

          echo $serviceName
          echo $imageVersion
          echo $resourceCpu
          echo $resourceMem


      #     applyKustomizeToDir ${{ inputs.kustomize_overlay_path }} \
      #       $serviceName $imageVersion $resourceCpu $resourceMem
      #
      # - name: Wait for Service Ready
      #   id: wait_ready
      #   run: |
      #     source $CONFIG_FILE
      #     source ./deployment_functions.sh
      #
      #     waitForServiceReady ${{ inputs.service_name }}
