name: Deploy SMTP Mock

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name'
        type: string
        required: true

jobs:
  deploy_smtp_mock:
    name: Deploy SMTP mock
    runs-on: [self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}"]
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    env:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Update Kubeconfig
        id: update_kubeconfig
        run: |
          set -eo pipefail

          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Apply Kube Files
        id: apply_kube_files
        run: |
          set -eo pipefail
          source $CONFIG_FILE
          source ./deployment_functions.sh

          applyKubeFile "thirdparty/smtp-mock/${ENVIRONMENT}/deployment.yaml" $SMTP_MOCK_SERVICE_NAME "" $SMTP_MOCK_RESOURCE_CPU $SMTP_MOCK_RESOURCE_MEM
          applyKubeFile "thirdparty/smtp-mock/${ENVIRONMENT}/service.yaml" $SMTP_MOCK_SERVICE_NAME

      - name: Wait for Service Readiness
        id: wait_ready
        run: |
          set -eo pipefail
          source $CONFIG_FILE
          source ./deployment_functions.sh

          waitForServiceReady $SMTP_MOCK_SERVICE_NAME
