name: Kafka Topics

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: environment
      delete_topics:
        description: Delete Kafka topics
        required: true
        type: boolean
        default: false
      delete_topics_prefix:
        description: Topics to delete name prefix (required if delete_topics == true)
        required: false
        type: string
      create_topics:
        description: Create topics
        required: true
        type: boolean
        default: false

jobs:
  create_runner:
    name: Create Self-Hosted Runner
    needs: []
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        index: [1]
      fail-fast: true
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Start GitHub Runner
        id: start_runner
        uses: pagopa/interop-github-runner-aws-create-action@main
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          iam_role_arn: ${{ secrets.ECS_IAM_ROLE_ARN }}
          ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
          ecs_task_definition: ${{ secrets.TASK_DEFINITION }}
          ecs_container_name: github-runner
          ecs_task_subnet_id: ${{ secrets.SUBNET_ID }}
          ecs_task_sec_group: ${{ secrets.SEC_GROUP_ID }}
          pat_token: ${{ secrets.BOT_TOKEN }}

  delete_topics:
    name: Delete Kafka Topics
    needs: [create_runner]
    runs-on: [self-hosted, "run_id:${{ github.run_id }}"]
    if: ${{ inputs.delete_topics }}
    working-directory: ./kafka/scripts
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
      DOMAIN_TOPIC_PREFIX: ${{ inputs.delete_topics_prefix }}
    run: |
      set -eou pipefail

      npm ci
      npm run kafka:deleteTopics

  create_topics:
    name: Create Kafka Topics
    needs: [create_runner, delete_topics]
    runs-on: [self-hosted, "run_id:${{ github.run_id }}"]
    if: ${{ always() && inputs.delete_topics }}
    working-directory: ./kafka/scripts
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
      TOPICS_PROPERTIES_PATH: ../topics/${{ inputs.environment }}
    run: |
      set -eou pipefail

      npm ci
      npm run kafka:createTopics

  delete_runner:
    name: Delete Self-Hosted Runner
    needs: [create_runner, delete_topics, create_topics]
    if: ${{ always() && needs.create_runner.result != 'skipped' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        index: [1]
      fail-fast: true
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Stop Github Runner
        id: stop_runner
        uses: pagopa/interop-github-runner-aws-cleanup-action@main
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          iam_role_arn: ${{ secrets.ECS_IAM_ROLE_ARN }}
          ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
          pat_token: ${{ secrets.BOT_TOKEN }}
