# TODO Temporary, just until we have test rds configured
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{SERVICE_NAME}}
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{SERVICE_NAME}}
          image: postgres:10.6
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USR
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PSW
  