apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PARTY_REGISTRY_CATEGORIES_URL: "{{PARTY_REGISTRY_CATEGORIES_URL}}"
  PARTY_REGISTRY_INSTITUTIONS_URL: "{{PARTY_REGISTRY_INSTITUTIONS_URL}}"
