apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PARTY_REGISTRY_CATEGORIES_URL: "http://{{PARTY_MOCK_REGISTRY_SERVICE_NAME}}:8088/{{PARTY_MOCK_REGISTRY_SERVICE_NAME}}/{{PARTY_MOCK_REGISTRY_INTERFACE_VERSION}}/opendata/categories"
  PARTY_REGISTRY_INSTITUTIONS_URL: "http://{{PARTY_MOCK_REGISTRY_SERVICE_NAME}}:8088/{{PARTY_MOCK_REGISTRY_SERVICE_NAME}}/{{PARTY_MOCK_REGISTRY_INTERFACE_VERSION}}/opendata/parties"