apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
data:
  PARTY_REGISTRY_CATEGORIES_URL: "{{PARTY_REGISTRY_CATEGORIES_URL}}"
  PARTY_REGISTRY_INSTITUTIONS_URL: "{{PARTY_REGISTRY_INSTITUTIONS_URL}}"
  MOCK_ORIGIN: "{{MOCK_ORIGIN}}"
  PARTY_MOCK_REGISTRY_INSTITUTIONS_URL: "{{PARTY_MOCK_REGISTRY_INSTITUTIONS_URL}}"
  PARTY_MOCK_REGISTRY_CATEGORIES_URL: "{{PARTY_MOCK_REGISTRY_CATEGORIES_URL}}"

  ACCEPTED_AUDIENCES: "{{INTERNAL_JWT_AUDIENCE}},{{UI_JWT_AUDIENCE}}"
