apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          env:
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: ACCEPTED_AUDIENCES
            - name: PARTY_REGISTRY_CATEGORIES_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_REGISTRY_CATEGORIES_URL
            - name: PARTY_REGISTRY_INSTITUTIONS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_REGISTRY_INSTITUTIONS_URL
            - name: PARTY_REGISTRY_AOO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_REGISTRY_AOO_URL
            - name: PARTY_REGISTRY_UO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{SERVICE_NAME}}
                  key: PARTY_REGISTRY_UO_URL
          volumeMounts:
            - name: categories-index-volume
              mountPath: /opt/docker/index/categories
            - name: institutions-index-volume
              mountPath: /opt/docker/index/institutions
            - name: aoo-index-volume
              mountPath: /opt/docker/index/aoo
            - name: uo-index-volume
              mountPath: /opt/docker/index/uo
      volumes:
        - name: categories-index-volume
          emptyDir: {}
        - name: institutions-index-volume
          emptyDir: {}
        - name: aoo-index-volume
          emptyDir: {}
        - name: uo-index-volume
          emptyDir: {}
